import * as XLSX from "xlsx";
import { parseEmployeeDate } from "./employee-import";

export const attendanceFields = [["employee","ID / NIK / Nama Karyawan"],["workDate","Tanggal"],["status","Status"],["checkIn","Jam Masuk"],["checkOut","Jam Pulang"],["notes","Catatan"]] as const;
const aliases:Record<string,string[]>={employee:["id karyawan","nik","nama","nama karyawan","karyawan","employee id"],workDate:["tanggal","tanggal kerja","work date","date"],status:["status","status absensi","kehadiran"],checkIn:["jam masuk","check in","check-in","masuk"],checkOut:["jam pulang","check out","check-out","pulang"],notes:["catatan","notes","keterangan"]};
const key=(v:unknown)=>String(v??"").trim().toLowerCase().replace(/\s+/g," ");
export function parseAttendanceWorkbook(buffer:Buffer){const book=XLSX.read(buffer,{type:"buffer",cellDates:true}),sheet=book.Sheets[book.SheetNames[0]],matrix=XLSX.utils.sheet_to_json<unknown[]>(sheet,{header:1,defval:"",raw:false});if(!matrix.length)throw new Error("File kosong");const headers=matrix[0].map(v=>String(v).trim()).filter(Boolean),rows=matrix.slice(1).filter(row=>row.some(v=>String(v).trim())).slice(0,5000).map(row=>Object.fromEntries(headers.map((h,i)=>[h,row[i]??""])));return{headers,rows,suggestedMapping:Object.fromEntries(attendanceFields.map(([f])=>[f,headers.find(h=>aliases[f].includes(key(h)))??""]))};}
export function attendanceDate(value:unknown){return parseEmployeeDate(value);}
export function attendanceTime(value:unknown){if(value instanceof Date)return {value:`${String(value.getUTCHours()).padStart(2,"0")}:${String(value.getUTCMinutes()).padStart(2,"0")}`};const raw=String(value??"").trim().replace(".",":");const match=raw.match(/^(\d{1,2}):(\d{2})(?::\d{2})?$/);if(!match)return raw?{value:null,warning:`Jam tidak valid: ${raw}`}:{value:null};const h=Number(match[1]),m=Number(match[2]);return h<24&&m<60?{value:`${String(h).padStart(2,"0")}:${String(m).padStart(2,"0")}`}:{value:null,warning:`Jam tidak valid: ${raw}`};}
export function attendanceStatus(value:unknown){const raw=key(value),map:Record<string,string>={hadir:"PRESENT",present:"PRESENT",terlambat:"LATE",late:"LATE","pulang cepat":"EARLY_LEAVE",absen:"ABSENT","tidak hadir":"ABSENT",absent:"ABSENT",cuti:"LEAVE",leave:"LEAVE",sakit:"SICK",sick:"SICK",izin:"PERMISSION",permission:"PERMISSION",libur:"HOLIDAY",holiday:"HOLIDAY",lembur:"OVERTIME",overtime:"OVERTIME"};return map[raw]??(raw.toUpperCase()||"PRESENT");}
