import {appUrl} from "@/lib/app-url";
import {requirePermission} from "@/lib/authorization";
import {db} from "@/lib/db";
import {NextRequest,NextResponse} from "next/server";
import {z} from "zod";
const base=z.object({id:z.string().cuid(),kind:z.enum(["branch","department","position"]),action:z.enum(["UPDATE","TOGGLE","DELETE"])});const update=z.object({code:z.string().trim().toUpperCase().regex(/^[A-Z0-9_-]{2,20}$/),name:z.string().trim().min(2).max(100)});
const moduleFor=(kind:"branch"|"department"|"position")=>kind==="branch"?"branches":kind==="department"?"departments":"positions";
export async function POST(request:NextRequest){try{const form=await request.formData(),parsed=base.parse(Object.fromEntries(form)),module=moduleFor(parsed.kind),tenant=await requirePermission(module,parsed.action==="DELETE"?"delete":"edit"),model=db[parsed.kind] as never as {findFirst(args:unknown):Promise<{id:string;code:string;name:string;deletedAt:Date|null}|null>;findFirstOrThrow(args:unknown):Promise<{id:string;code:string;name:string;deletedAt:Date|null}>;update(args:unknown):Promise<unknown>;delete(args:unknown):Promise<unknown>},record=await model.findFirstOrThrow({where:{id:parsed.id,companyId:tenant.companyId}});
if(parsed.action==="UPDATE"){const data=update.parse(Object.fromEntries(form)),duplicate=await model.findFirst({where:{companyId:tenant.companyId,code:data.code,id:{not:record.id}}});if(duplicate)throw new Error("DUPLICATE");await model.update({where:{id:record.id},data});await db.auditLog.create({data:{companyId:tenant.companyId,actorUserId:tenant.session.userId,action:"UPDATE",module,entityType:parsed.kind,entityId:record.id,previousValue:JSON.parse(JSON.stringify(record)),newValue:data}});}
if(parsed.action==="TOGGLE"){const deletedAt=record.deletedAt?null:new Date();await model.update({where:{id:record.id},data:{deletedAt}});await db.auditLog.create({data:{companyId:tenant.companyId,actorUserId:tenant.session.userId,action:deletedAt?"DEACTIVATE":"ACTIVATE",module,entityType:parsed.kind,entityId:record.id}});}
if(parsed.action==="DELETE"){const used=parsed.kind==="branch"?await db.employee.count({where:{companyId:tenant.companyId,branchId:record.id}})+await db.shift.count({where:{companyId:tenant.companyId,branchId:record.id}})+await db.attendance.count({where:{companyId:tenant.companyId,branchId:record.id}})+await db.schedule.count({where:{companyId:tenant.companyId,branchId:record.id}}):parsed.kind==="department"?await db.employee.count({where:{companyId:tenant.companyId,departmentId:record.id}})+await db.shift.count({where:{companyId:tenant.companyId,departmentId:record.id}})+await db.schedule.count({where:{companyId:tenant.companyId,departmentId:record.id}}):await db.employee.count({where:{companyId:tenant.companyId,positionId:record.id}});if(used)return NextResponse.redirect(new URL(`/organization?error=used&kind=${parsed.kind}`,appUrl(request)),303);await model.delete({where:{id:record.id}});await db.auditLog.create({data:{companyId:tenant.companyId,actorUserId:tenant.session.userId,action:"DELETE",module,entityType:parsed.kind,entityId:record.id,previousValue:JSON.parse(JSON.stringify(record))}});}
return NextResponse.redirect(new URL(`/organization?saved=${parsed.action.toLowerCase()}`,appUrl(request)),303);}catch(error){console.error("ORGANIZATION_MANAGE",error);return NextResponse.redirect(new URL(`/organization?error=${error instanceof Error&&error.message==="DUPLICATE"?"duplicate":"failed"}`,appUrl(request)),303);}}
