import { requirePermission } from "@/lib/authorization";
import { db } from "@/lib/db";
import { hasPermission } from "@/lib/permissions";
import { redirect } from "next/navigation";
import { EmployeeImportDialog } from "../employees/EmployeeImportDialog";

export default async function ContractsPage({ searchParams }: { searchParams: Promise<{ saved?: string; error?: string; status?: string }> }) {
  let tenant; try { tenant = await requirePermission("employees", "view"); } catch { redirect("/dashboard"); }
  const query = await searchParams, now = new Date(), next30 = new Date(now.getTime() + 30 * 86400000);
  const employees = await db.employee.findMany({ where: { companyId: tenant.companyId, deletedAt: null, ...(query.status === "EXPIRING" ? { contractEndDate: { gte: now, lte: next30 } } : query.status === "EXPIRED" ? { contractEndDate: { lt: now } } : query.status === "ACTIVE" ? { OR: [{ contractEndDate: null }, { contractEndDate: { gte: now } }] } : {}) }, select: { id: true, employeeNumber: true, fullName: true, contractTypeLabel: true, employmentType: true, contractStartDate: true, contractEndDate: true }, orderBy: [{ contractEndDate: "asc" }, { fullName: "asc" }] });
  const canEdit = hasPermission(tenant.membership.role.permissions, "employees", "edit"), canCreate = hasPermission(tenant.membership.role.permissions, "employees", "create"), canExport = hasPermission(tenant.membership.role.permissions, "employees", "export");
  const format = (date: Date | null) => date?.toISOString().slice(0,10) ?? "-", state = (date: Date | null) => !date ? "Tanpa batas akhir" : date < now ? "Berakhir" : date <= next30 ? "Segera berakhir" : "Aktif";
  return <main className="settings-page"><section className="settings-card"><header><div><span className="eyebrow">KEPEGAWAIAN</span><h1>Kontrak Karyawan</h1><p>Pantau dan perbarui kontrak khusus {tenant.membership.company.name}.</p></div><a href="/dashboard">Kembali</a></header>
    {query.saved && <div className="form-success">Kontrak berhasil diperbarui.</div>}{query.error && <div className="form-error">Kontrak gagal diperbarui. Periksa tanggal dan hak akses.</div>}
    <div className="standard-toolbar"><div className="toolbar-actions"><a href="/contracts">Semua</a><a href="/contracts?status=ACTIVE">Aktif</a><a href="/contracts?status=EXPIRING">Berakhir ≤ 30 Hari</a><a href="/contracts?status=EXPIRED">Sudah Berakhir</a>{canCreate&&<EmployeeImportDialog/>}{canCreate&&<a href="/api/employees/template">Download Template</a>}{canExport&&<a href={`/api/contracts/export${query.status?`?status=${query.status}`:""}`}>Export Excel</a>}</div></div>
    <div className="contract-list">{employees.map(employee=><article key={employee.id}><div><strong>{employee.fullName}</strong><small>{employee.employeeNumber} · {employee.contractTypeLabel??employee.employmentType??"Jenis belum diisi"}</small></div><span>{format(employee.contractStartDate)} → {format(employee.contractEndDate)}</span><b>{state(employee.contractEndDate)}</b>{canEdit&&<details><summary>Edit kontrak</summary><form action="/api/contracts" method="post"><input type="hidden" name="employeeId" value={employee.id}/><label>Jenis kontrak<input name="contractTypeLabel" defaultValue={employee.contractTypeLabel??""} maxLength={80}/></label><label>Mulai kontrak<input type="date" name="contractStartDate" defaultValue={employee.contractStartDate?.toISOString().slice(0,10)??""}/></label><label>Berakhir kontrak<input type="date" name="contractEndDate" defaultValue={employee.contractEndDate?.toISOString().slice(0,10)??""}/></label><button>Simpan</button></form></details>}</article>)}{employees.length===0&&<p>Belum ada kontrak pada filter ini.</p>}</div>
  </section></main>;
}
