import { appUrl } from "@/lib/app-url";
import { requirePermission } from "@/lib/authorization";
import { db } from "@/lib/db";
import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";

const base=z.object({id:z.string().cuid(),action:z.enum(["UPDATE","TOGGLE","DELETE","DUPLICATE"])});
const fields=z.object({code:z.string().trim().toUpperCase().regex(/^[A-Z0-9_-]{1,20}$/),name:z.string().trim().min(2).max(60),startTime:z.string().regex(/^\d{2}:\d{2}$/),endTime:z.string().regex(/^\d{2}:\d{2}$/),breakMinutes:z.coerce.number().int().min(0).max(480),lateToleranceMin:z.coerce.number().int().min(0).max(180),minStaff:z.coerce.number().int().min(0).max(10000),maxStaff:z.preprocess(value=>value===""?null:value,z.coerce.number().int().min(1).max(10000).nullable()),color:z.string().regex(/^#[0-9A-Fa-f]{6}$/)}).refine(data=>data.maxStaff===null||data.maxStaff>=data.minStaff);
export async function POST(request:NextRequest){
  try{const form=await request.formData(),parsed=base.parse(Object.fromEntries(form)),permission=parsed.action==="DELETE"?"delete":"edit",tenant=await requirePermission("shifts",permission),shift=await db.shift.findFirstOrThrow({where:{id:parsed.id,companyId:tenant.companyId}});
    if(parsed.action==="UPDATE"){const data=fields.parse(Object.fromEntries(form));const duplicate=await db.shift.findFirst({where:{companyId:tenant.companyId,code:data.code,id:{not:shift.id}}});if(duplicate)throw new Error("DUPLICATE");await db.shift.update({where:{id:shift.id},data});await db.auditLog.create({data:{companyId:tenant.companyId,actorUserId:tenant.session.userId,action:"UPDATE",module:"shifts",entityType:"Shift",entityId:shift.id,previousValue:JSON.parse(JSON.stringify(shift)),newValue:data}});}
    if(parsed.action==="TOGGLE"){const deletedAt=shift.deletedAt?null:new Date();await db.shift.update({where:{id:shift.id},data:{deletedAt}});await db.auditLog.create({data:{companyId:tenant.companyId,actorUserId:tenant.session.userId,action:deletedAt?"DEACTIVATE":"ACTIVATE",module:"shifts",entityType:"Shift",entityId:shift.id}});}
    if(parsed.action==="DELETE"){if(await db.scheduleAssignment.count({where:{companyId:tenant.companyId,shiftId:shift.id}}))return NextResponse.redirect(new URL("/shifts?error=used",appUrl(request)),303);await db.shift.delete({where:{id:shift.id}});await db.auditLog.create({data:{companyId:tenant.companyId,actorUserId:tenant.session.userId,action:"DELETE",module:"shifts",entityType:"Shift",entityId:shift.id,previousValue:JSON.parse(JSON.stringify(shift))}});}
    if(parsed.action==="DUPLICATE"){let code=`${shift.code}-COPY`.slice(0,20),number=2;while(await db.shift.count({where:{companyId:tenant.companyId,code}}))code=`${shift.code.slice(0,14)}-${number++}`;const copy=await db.shift.create({data:{companyId:tenant.companyId,code,name:`${shift.name} Salinan`,startTime:shift.startTime,endTime:shift.endTime,breakMinutes:shift.breakMinutes,lateToleranceMin:shift.lateToleranceMin,minStaff:shift.minStaff,maxStaff:shift.maxStaff,color:shift.color,branchId:shift.branchId,departmentId:shift.departmentId}});await db.auditLog.create({data:{companyId:tenant.companyId,actorUserId:tenant.session.userId,action:"DUPLICATE",module:"shifts",entityType:"Shift",entityId:copy.id,newValue:{sourceId:shift.id,code}}});}
    return NextResponse.redirect(new URL("/shifts?saved=1",appUrl(request)),303);
  }catch(error){console.error("SHIFT_MANAGE",error);return NextResponse.redirect(new URL(`/shifts?error=${error instanceof Error&&error.message==="DUPLICATE"?"duplicate":"failed"}`,appUrl(request)),303);}
}
