import { appUrl } from "@/lib/app-url";import { requirePermission } from "@/lib/authorization";import { db } from "@/lib/db";import { NextRequest,NextResponse } from "next/server";import { z } from "zod";
const schema=z.object({action:z.enum(["CREATE","GENERATE","UPDATE_ITEM","FINALIZE","MARK_PAID","REOPEN","DELETE"]),id:z.string().optional(),periodId:z.string().optional(),year:z.coerce.number().int().min(2020).max(2100).optional(),month:z.coerce.number().int().min(1).max(12).optional(),paymentDate:z.string().optional(),baseSalary:z.string().optional(),allowance:z.string().optional(),overtimePay:z.string().optional(),bonus:z.string().optional(),deduction:z.string().optional(),notes:z.string().trim().max(500).optional()});
const money=(v?:string)=>{const n=Number((v||"0").replace(/[^0-9.-]/g,""));if(!Number.isFinite(n)||n<0)throw new Error("MONEY");return Math.round(n)};
export async function POST(req:NextRequest){let target="/payroll";try{const p=schema.parse(Object.fromEntries(await req.formData())),perm=p.action==="CREATE"||p.action==="GENERATE"?"create":p.action==="DELETE"?"delete":["FINALIZE","MARK_PAID"].includes(p.action)?"approve":"edit",tenant=await requirePermission("payroll",perm);
if(p.action==="CREATE"){if(!p.year||!p.month)throw new Error();const names=["","Januari","Februari","Maret","April","Mei","Juni","Juli","Agustus","September","Oktober","November","Desember"],item=await db.payrollPeriod.create({data:{companyId:tenant.companyId,year:p.year,month:p.month,name:`Payroll ${names[p.month]} ${p.year}`}});target=`/payroll?periodId=${item.id}`;await db.auditLog.create({data:{companyId:tenant.companyId,actorUserId:tenant.session.userId,action:"CREATE",module:"payroll",entityType:"PayrollPeriod",entityId:item.id,newValue:{year:p.year,month:p.month}}});}
else{const periodId=p.periodId||p.id,targetPeriod=await db.payrollPeriod.findFirstOrThrow({where:{id:periodId,companyId:tenant.companyId}});target=`/payroll?periodId=${targetPeriod.id}`;
if(p.action==="GENERATE"){if(targetPeriod.status!=="DRAFT")throw new Error();const employees=await db.employee.findMany({where:{companyId:tenant.companyId,deletedAt:null,employmentStatus:"ACTIVE"}});await db.$transaction(employees.map(e=>db.payrollItem.upsert({where:{payrollPeriodId_employeeId:{payrollPeriodId:targetPeriod.id,employeeId:e.id}},create:{companyId:tenant.companyId,payrollPeriodId:targetPeriod.id,employeeId:e.id,baseSalary:e.baseSalary??0,netSalary:e.baseSalary??0},update:{}})));}
if(p.action==="UPDATE_ITEM"){if(targetPeriod.status!=="DRAFT"||!p.id)throw new Error();const item=await db.payrollItem.findFirstOrThrow({where:{id:p.id,companyId:tenant.companyId,payrollPeriodId:targetPeriod.id}}),baseSalary=money(p.baseSalary),allowance=money(p.allowance),overtimePay=money(p.overtimePay),bonus=money(p.bonus),deduction=money(p.deduction),netSalary=Math.max(0,baseSalary+allowance+overtimePay+bonus-deduction);await db.payrollItem.update({where:{id:item.id},data:{baseSalary,allowance,overtimePay,bonus,deduction,netSalary,notes:p.notes||null}});await db.auditLog.create({data:{companyId:tenant.companyId,actorUserId:tenant.session.userId,action:"UPDATE",module:"payroll",entityType:"PayrollItem",entityId:item.id,previousValue:{netSalary:item.netSalary.toString()},newValue:{baseSalary,allowance,overtimePay,bonus,deduction,netSalary}}});}
if(p.action==="FINALIZE"){if(targetPeriod.status!=="DRAFT"||!(await db.payrollItem.count({where:{payrollPeriodId:targetPeriod.id,companyId:tenant.companyId}})))throw new Error();await db.payrollPeriod.update({where:{id:targetPeriod.id},data:{status:"FINALIZED",finalizedAt:new Date()}});}
if(p.action==="MARK_PAID"){if(targetPeriod.status!=="FINALIZED")throw new Error();await db.payrollPeriod.update({where:{id:targetPeriod.id},data:{status:"PAID",paymentDate:p.paymentDate?new Date(`${p.paymentDate}T00:00:00.000Z`):new Date()}});}
if(p.action==="REOPEN"){if(targetPeriod.status==="PAID")throw new Error();await db.payrollPeriod.update({where:{id:targetPeriod.id},data:{status:"DRAFT",finalizedAt:null}});}
if(p.action==="DELETE"){if(targetPeriod.status!=="DRAFT")throw new Error();await db.payrollPeriod.delete({where:{id:targetPeriod.id}});target="/payroll";}
if(p.action!=="UPDATE_ITEM")await db.auditLog.create({data:{companyId:tenant.companyId,actorUserId:tenant.session.userId,action:p.action,module:"payroll",entityType:"PayrollPeriod",entityId:targetPeriod.id,previousValue:{status:targetPeriod.status},newValue:{status:p.action}}});}
return NextResponse.redirect(new URL(`${target}${target.includes("?")?"&":"?"}saved=1`,appUrl(req)),303);}catch{return NextResponse.redirect(new URL(`${target}${target.includes("?")?"&":"?"}error=1`,appUrl(req)),303);}}
