"use client";
import { useState } from "react";

type PreviewRow = { row:number; date:string; normalizedDate:string; employeeId:string; employeeLabel:string; shiftId:string; shiftLabel:string; type:"WORK"|"OFF"; notes:string; status:"VALID"|"ERROR"; errors:string[] };
type Preview = { filename:string; rows:PreviewRow[]; summary:{total:number;valid:number;error:number} };
export function ScheduleImportDialog({month,branchId,departmentId}:{month:string;branchId:string;departmentId:string}) {
  const [open,setOpen]=useState(false),[busy,setBusy]=useState(false),[preview,setPreview]=useState<Preview|null>(null),[result,setResult]=useState<{created:number;updated:number}|null>(null);
  async function upload(file:File){setBusy(true);const body=new FormData();body.set("file",file);body.set("month",month);const response=await fetch("/api/schedules/import/preview",{method:"POST",body});const json=await response.json();setBusy(false);if(!response.ok)return alert(json.error);setPreview(json);}
  async function commit(){if(!preview)return;setBusy(true);const rows=preview.rows.filter(row=>row.status==="VALID").map(row=>({date:row.normalizedDate,employeeId:row.employeeId,shiftId:row.shiftId,type:row.type,notes:row.notes}));const response=await fetch("/api/schedules/import/commit",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({filename:preview.filename,month,branchId,departmentId,rows})});const json=await response.json();setBusy(false);if(!response.ok)return alert(json.error);setResult(json);}
  function close(){setOpen(false);setPreview(null);setResult(null);if(result)location.href=`/schedules?month=${month}&branchId=${branchId}&departmentId=${departmentId}&saved=import`;}
  return <><button type="button" className="secondary-button" onClick={()=>setOpen(true)}>Import Jadwal</button>{open&&<div className="modal-backdrop"><section className="import-dialog"><header><div><b>Import Jadwal Excel</b><small>Upload → Preview → Konfirmasi</small></div><button type="button" onClick={close}>×</button></header>{!preview&&!result&&<div className="import-stage"><h3>Pilih file jadwal</h3><p>Bulan tujuan: <b>{month}</b>. Karyawan dicocokkan melalui ID atau nama. Shift dicocokkan melalui kode atau nama.</p><input type="file" accept=".xlsx,.xls" disabled={busy} onChange={event=>event.target.files?.[0]&&void upload(event.target.files[0])}/><a href="/api/schedules/template">Download Template Excel</a></div>}{preview&&!result&&<div className="import-stage"><h3>Preview & Validasi</h3><div className="preview-summary"><b>Total<span>{preview.summary.total}</span></b><b>Siap Import<span>{preview.summary.valid}</span></b><b>Error<span>{preview.summary.error}</span></b></div><div className="preview-table">{preview.rows.slice(0,200).map(row=><div key={row.row}><span>{row.row}</span><strong>{row.employeeLabel}<small>{row.normalizedDate||row.date} • {row.shiftLabel}</small></strong><b className={`row-${row.status.toLowerCase()}`}>{row.status}</b><small>{row.errors.join("; ")}</small></div>)}</div><p>Baris error tidak akan masuk. Baris valid akan membuat atau memperbarui jadwal DRAFT.</p><button type="button" onClick={()=>setPreview(null)}>Ganti File</button><button type="button" disabled={busy||!preview.summary.valid} onClick={()=>void commit()}>{busy?"Mengimport...":`Import ${preview.summary.valid} Data Valid`}</button></div>}{result&&<div className="import-stage"><h3>Import Jadwal Selesai</h3><div className="preview-summary"><b>Data baru<span>{result.created}</span></b><b>Diperbarui<span>{result.updated}</span></b></div><button type="button" onClick={close}>Lihat Jadwal</button></div>}</section></div>}</>;
}
