import { requirePermission } from "@/lib/authorization";
import { db } from "@/lib/db";
import { importKey, importText, normalizeNationalId, normalizePhones, parseEmployeeDate, phoneDigits, safeCode, tidyEmployeeText } from "@/lib/employee-import";
import { Prisma } from "@prisma/client";
import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";

const schema = z.object({ filename: z.string().max(200), rows: z.array(z.record(z.string(), z.unknown())).max(5000), mapping: z.record(z.string(), z.string()), dryRun: z.boolean(), duplicateStrategy: z.enum(["SKIP", "UPDATE", "NEW"]), createMasters: z.boolean(), importWarnings: z.boolean().default(true) });
type ImportStatus = "VALID" | "WARNING" | "ERROR" | "DUPLICATE" | "UPDATE";
type ImportItem = { source: Record<string, unknown>; fullName: string; employeeNumber: string; nationalId: string; email: string; phone: string; joinDate: Date | null; contractEndDate: Date | null; stopDate: Date | null; birthDate: Date | null; positionName: string; departmentName: string; branchName: string; placeOfBirth: string; address: string; maritalStatus: string; religion: string; employeeStatusLabel: string; duplicateId: string | null; status: ImportStatus };

const internalStatus = (label: string): "ACTIVE" | "INACTIVE" | "RESIGNED" | "TERMINATED" => { const value = importKey(label); if (["nonaktif", "pensiun"].includes(value)) return "INACTIVE"; if (["resign", "mengundurkan diri"].includes(value)) return "RESIGNED"; if (["phk", "terminated", "diberhentikan"].includes(value)) return "TERMINATED"; return "ACTIVE"; };

export async function POST(request: NextRequest) {
  try {
    const tenant = await requirePermission("employees", "create"), parsed = schema.parse(await request.json());
    const mapped = (row: Record<string, unknown>, field: string) => parsed.mapping[field] ? row[parsed.mapping[field]] : "";
    const [existing, positions, departments, branches, masters] = await Promise.all([
      db.employee.findMany({ where: { companyId: tenant.companyId, deletedAt: null } }), db.position.findMany({ where: { companyId: tenant.companyId, deletedAt: null } }), db.department.findMany({ where: { companyId: tenant.companyId, deletedAt: null } }), db.branch.findMany({ where: { companyId: tenant.companyId, deletedAt: null } }), db.masterData.findMany({ where: { companyId: tenant.companyId, deletedAt: null } }),
    ]);
    const byNationalId = new Map(existing.filter(item => item.nationalId).map(item => [normalizeNationalId(item.nationalId), item])), byEmail = new Map(existing.filter(item => item.email).map(item => [importKey(item.email), item])), byPhone = new Map(existing.filter(item => item.phone).map(item => [phoneDigits(item.phone), item])), byNameBirth = new Map(existing.filter(item => item.birthDate).map(item => [`${importKey(item.fullName)}|${item.birthDate!.toISOString().slice(0, 10)}`, item]));
    const positionMap = new Map(positions.map(item => [importKey(item.name), item.id])), departmentMap = new Map(departments.map(item => [importKey(item.name), item.id])), branchMap = new Map(branches.map(item => [importKey(item.name), item.id])), masterKeys = new Set(masters.map(item => `${item.category}|${importKey(item.name)}`));
    const items: ImportItem[] = [], previewRows: Array<Record<string, unknown>> = [];

    for (let index = 0; index < parsed.rows.length; index++) {
      const row = parsed.rows[index], errors: string[] = [], warnings: string[] = [], fullName = tidyEmployeeText(mapped(row, "fullName"));
      if (!fullName) errors.push("Nama karyawan kosong");
      const emailRaw = importKey(mapped(row, "email")), emailValid = !emailRaw || z.string().email().safeParse(emailRaw).success; if (!emailValid) warnings.push("Format email tidak valid; email dikosongkan");
      const nationalIdOriginal = importText(mapped(row, "nationalId")), nationalId = normalizeNationalId(nationalIdOriginal); if (nationalId && nationalId.length !== 16) warnings.push(`NIK bukan 16 digit: ${nationalIdOriginal}`);
      const phone = normalizePhones(mapped(row, "phone")); if (phone && phoneDigits(phone).length < 9) warnings.push(`Nomor telepon perlu diperiksa: ${phone}`);
      const join = parseEmployeeDate(mapped(row, "joinDate")), contractEnd = parseEmployeeDate(mapped(row, "contractEndDate")), stop = parseEmployeeDate(mapped(row, "stopDate")), birth = parseEmployeeDate(mapped(row, "birthDate"));
      for (const date of [join, contractEnd, stop, birth]) if (date.warning) warnings.push(date.warning);
      const positionName = tidyEmployeeText(mapped(row, "position")), departmentName = tidyEmployeeText(mapped(row, "department")), branchName = tidyEmployeeText(mapped(row, "branch")), employeeStatusLabel = tidyEmployeeText(mapped(row, "employeeStatusLabel")), maritalStatus = tidyEmployeeText(mapped(row, "maritalStatus")), religion = tidyEmployeeText(mapped(row, "religion"));
      if (positionName && !positionMap.has(importKey(positionName))) warnings.push(`Master Data Baru — Jabatan: ${positionName}`); if (departmentName && !departmentMap.has(importKey(departmentName))) warnings.push(`Master Data Baru — Divisi: ${departmentName}`); if (branchName && !branchMap.has(importKey(branchName))) warnings.push(`Master Data Baru — Cabang: ${branchName}`);
      for (const [category, label] of [["EMPLOYEE_STATUS", employeeStatusLabel], ["MARITAL_STATUS", maritalStatus], ["RELIGION", religion]] as const) if (label && !masterKeys.has(`${category}|${importKey(label)}`)) warnings.push(`Master Data Baru — ${category}: ${label}`);
      const duplicate = (nationalId ? byNationalId.get(nationalId) : undefined) || (emailRaw ? byEmail.get(emailRaw) : undefined) || (phoneDigits(phone) ? byPhone.get(phoneDigits(phone)) : undefined) || (birth.date ? byNameBirth.get(`${importKey(fullName)}|${birth.date.toISOString().slice(0, 10)}`) : undefined);
      let status: ImportStatus = errors.length ? "ERROR" : warnings.length ? "WARNING" : "VALID"; if (!errors.length && duplicate) status = parsed.duplicateStrategy === "UPDATE" ? "UPDATE" : parsed.duplicateStrategy === "NEW" ? status : "DUPLICATE";
      items.push({ source: row, fullName, employeeNumber: importText(mapped(row, "employeeNumber")).toUpperCase(), nationalId, email: emailValid ? emailRaw : "", phone, joinDate: join.date, contractEndDate: contractEnd.date, stopDate: stop.date, birthDate: birth.date, positionName, departmentName, branchName, placeOfBirth: tidyEmployeeText(mapped(row, "placeOfBirth")), address: importText(mapped(row, "address")), maritalStatus, religion, employeeStatusLabel, duplicateId: duplicate?.id ?? null, status });
      previewRows.push({ row: index + 2, status, errors, warnings, name: fullName, nationalIdOriginal, nationalId, phone, original: row });
    }
    const summary = { total: previewRows.length, valid: previewRows.filter(r => r.status === "VALID").length, warning: previewRows.filter(r => r.status === "WARNING").length, error: previewRows.filter(r => r.status === "ERROR").length, duplicate: previewRows.filter(r => r.status === "DUPLICATE").length, update: previewRows.filter(r => r.status === "UPDATE").length };
    if (parsed.dryRun) return NextResponse.json({ rows: previewRows, summary });

    const accepted = items.filter(item => item.status !== "ERROR" && item.status !== "DUPLICATE" && (parsed.importWarnings || item.status !== "WARNING")); let created = 0, updated = 0;
    const batch = await db.$transaction(async tx => {
      const createdBatch = await tx.importBatch.create({ data: { companyId: tenant.companyId, actorUserId: tenant.session.userId, filename: parsed.filename, totalRows: items.length, warningRows: summary.warning, errorRows: summary.error, skippedRows: items.length - accepted.length, errorData: previewRows.filter(row => row.status === "ERROR") as Prisma.InputJsonValue } });
      const createMaster = async (category: string, name: string) => { const masterKey = `${category}|${importKey(name)}`; if (!name || masterKeys.has(masterKey) || !parsed.createMasters) return; await tx.masterData.create({ data: { companyId: tenant.companyId, category, code: safeCode(name, category.slice(0, 3)), name } }); masterKeys.add(masterKey); };
      if (parsed.createMasters) {
        for (const name of ["Aktif", "Training", "Probation", "Kontrak", "Tetap", "Magang", "Cuti", "Nonaktif", "Resign", "PHK", "Pensiun"]) await createMaster("EMPLOYEE_STATUS", name);
        for (const name of ["Lajang", "Menikah", "Cerai Hidup", "Cerai Mati"]) await createMaster("MARITAL_STATUS", name);
        for (const name of ["Islam", "Kristen Protestan", "Katolik", "Hindu", "Buddha", "Konghucu", "Kepercayaan Lainnya"]) await createMaster("RELIGION", name);
      }
      const relationMaster = async (model: "position" | "department" | "branch", name: string, map: Map<string, string>) => { if (!name) return undefined; const current = map.get(importKey(name)); if (current) return current; if (!parsed.createMasters) return undefined; const record = await (tx[model] as never as { create(args: { data: { companyId: string; name: string; code: string } }): Promise<{ id: string }> }).create({ data: { companyId: tenant.companyId, name, code: safeCode(name, model.slice(0, 3)) } }); map.set(importKey(name), record.id); return record.id; };
      for (let index = 0; index < accepted.length; index++) {
        const item = accepted[index], positionId = await relationMaster("position", item.positionName, positionMap), departmentId = await relationMaster("department", item.departmentName, departmentMap), branchId = await relationMaster("branch", item.branchName, branchMap);
        await createMaster("EMPLOYEE_STATUS", item.employeeStatusLabel); await createMaster("MARITAL_STATUS", item.maritalStatus); await createMaster("RELIGION", item.religion);
        const has = (field: string) => Boolean(importText(mapped(item.source, field)));
        const data: Prisma.EmployeeUpdateInput = { fullName: item.fullName, ...(has("nationalId") ? { nationalId: item.nationalId || null } : {}), ...(has("email") && item.email ? { email: item.email } : {}), ...(has("phone") ? { phone: item.phone || null } : {}), ...(has("joinDate") && item.joinDate ? { joinDate: item.joinDate } : {}), ...(has("contractEndDate") && item.contractEndDate ? { contractEndDate: item.contractEndDate } : {}), ...(has("stopDate") && item.stopDate ? { stopDate: item.stopDate } : {}), ...(has("birthDate") && item.birthDate ? { birthDate: item.birthDate } : {}), ...(has("placeOfBirth") ? { placeOfBirth: item.placeOfBirth || null } : {}), ...(has("address") ? { address: item.address || null } : {}), ...(has("maritalStatus") ? { maritalStatus: item.maritalStatus || null } : {}), ...(has("religion") ? { religion: item.religion || null } : {}), ...(has("employeeStatusLabel") ? { employeeStatusLabel: item.employeeStatusLabel || null, employmentStatus: internalStatus(item.employeeStatusLabel) } : {}), ...(positionId ? { position: { connect: { id: positionId } } } : {}), ...(departmentId ? { department: { connect: { id: departmentId } } } : {}), ...(branchId ? { branch: { connect: { id: branchId } } } : {}) };
        if (item.duplicateId && parsed.duplicateStrategy === "UPDATE") { const previous = await tx.employee.findFirstOrThrow({ where: { id: item.duplicateId, companyId: tenant.companyId } }); await tx.employee.update({ where: { id: previous.id }, data }); updated++; await tx.auditLog.create({ data: { companyId: tenant.companyId, actorUserId: tenant.session.userId, action: "IMPORT_UPDATE", module: "employees", entityType: "Employee", entityId: previous.id, previousValue: previous as unknown as Prisma.InputJsonValue, newValue: data as Prisma.InputJsonValue } }); }
        else { const employeeNumber = item.employeeNumber || `EMP-${createdBatch.id.slice(-6).toUpperCase()}-${String(index + 1).padStart(4, "0")}`; const employee = await tx.employee.create({ data: { companyId: tenant.companyId, importBatchId: createdBatch.id, employeeNumber, fullName: item.fullName, employmentType: null, ...(item.nationalId ? { nationalId: item.nationalId } : {}), ...(item.email ? { email: item.email } : {}), ...(item.phone ? { phone: item.phone } : {}), ...(item.joinDate ? { joinDate: item.joinDate } : {}), ...(item.contractEndDate ? { contractEndDate: item.contractEndDate } : {}), ...(item.stopDate ? { stopDate: item.stopDate } : {}), ...(item.birthDate ? { birthDate: item.birthDate } : {}), ...(item.placeOfBirth ? { placeOfBirth: item.placeOfBirth } : {}), ...(item.address ? { address: item.address } : {}), ...(item.maritalStatus ? { maritalStatus: item.maritalStatus } : {}), ...(item.religion ? { religion: item.religion } : {}), ...(item.employeeStatusLabel ? { employeeStatusLabel: item.employeeStatusLabel, employmentStatus: internalStatus(item.employeeStatusLabel) } : {}), ...(positionId ? { positionId } : {}), ...(departmentId ? { departmentId } : {}), ...(branchId ? { branchId } : {}) } }); created++; await tx.auditLog.create({ data: { companyId: tenant.companyId, actorUserId: tenant.session.userId, action: "IMPORT_CREATE", module: "employees", entityType: "Employee", entityId: employee.id, newValue: { batchId: createdBatch.id, employeeNumber, fullName: item.fullName } } }); }
      }
      await tx.importBatch.update({ where: { id: createdBatch.id }, data: { createdRows: created, updatedRows: updated } }); await tx.auditLog.create({ data: { companyId: tenant.companyId, actorUserId: tenant.session.userId, action: "IMPORT", module: "employees", entityType: "ImportBatch", entityId: createdBatch.id, newValue: { filename: parsed.filename, total: items.length, created, updated, skipped: items.length - accepted.length } } }); return createdBatch;
    }, { timeout: 120000 });
    return NextResponse.json({ ok: true, batchId: batch.id, created, updated, skipped: items.length - accepted.length, warning: summary.warning, errors: previewRows.filter(item => item.status === "ERROR") });
  } catch (error) { console.error("EMPLOYEE_IMPORT_COMMIT", error); return NextResponse.json({ error: error instanceof Error ? `Import gagal: ${error.message}` : "Import gagal divalidasi atau tidak diizinkan" }, { status: 400 }); }
}
