import { requirePermission } from "@/lib/authorization";
import { db } from "@/lib/db";
import { hasPermission } from "@/lib/permissions";
import { candidateStages, stageLabels } from "@/lib/recruitment";
import { redirect } from "next/navigation";
import { ConfirmRecruitmentForm } from "./RecruitmentActions";

export default async function RecruitmentPage({ searchParams }: { searchParams: Promise<{ stage?: string; vacancyId?: string; q?: string; saved?: string; error?: string }> }) {
  let tenant; try { tenant = await requirePermission("recruitment", "view"); } catch { redirect("/dashboard"); }
  const query = await searchParams, stage = candidateStages.includes(query.stage as never) ? query.stage : "", vacancyId = query.vacancyId ?? "", q = query.q?.trim() ?? "";
  const [vacancies, candidates, branches, departments, positions] = await Promise.all([
    db.jobVacancy.findMany({ where: { companyId: tenant.companyId, deletedAt: null }, include: { _count: { select: { candidates: true } } }, orderBy: [{ status: "asc" }, { createdAt: "desc" }] }),
    db.candidate.findMany({ where: { companyId: tenant.companyId, deletedAt: null, ...(stage ? { stage } : {}), ...(vacancyId ? { vacancyId } : {}), ...(q ? { OR: [{ fullName: { contains: q, mode: "insensitive" } }, { email: { contains: q, mode: "insensitive" } }, { phone: { contains: q } }] } : {}) }, include: { vacancy: { select: { title: true } }, employee: { select: { id: true, employeeNumber: true } }, documents: { where: { deletedAt: null }, orderBy: { createdAt: "desc" } }, tasks: { where: { deletedAt: null }, orderBy: [{ status: "asc" }, { createdAt: "asc" }] } }, orderBy: { createdAt: "desc" } }),
    db.branch.findMany({ where: { companyId: tenant.companyId, deletedAt: null }, orderBy: { name: "asc" } }),
    db.department.findMany({ where: { companyId: tenant.companyId, deletedAt: null }, orderBy: { name: "asc" } }),
    db.position.findMany({ where: { companyId: tenant.companyId, deletedAt: null }, orderBy: { name: "asc" } }),
  ]);
  const permissions = tenant.membership.role.permissions, canCreate = hasPermission(permissions, "recruitment", "create"), canEdit = hasPermission(permissions, "recruitment", "edit"), canDelete = hasPermission(permissions, "recruitment", "delete");
  return <main className="settings-page"><section className="settings-card recruitment-page"><header><div><span className="eyebrow">PANBOY HR</span><h1>Rekrutmen & Onboarding</h1><p>Kelola lowongan, kandidat, penerimaan, dan persiapan kerja {tenant.membership.company.name}.</p></div><a href="/dashboard">Kembali</a></header>
    {query.saved && <div className="form-success">Data rekrutmen berhasil diproses.</div>}{query.error && <div className="form-error">Operasi gagal ({query.error}). Periksa data, duplikat nomor karyawan, dan hak akses.</div>}
    <div className="recruitment-stats"><article><b>{vacancies.filter(x => x.status === "OPEN").length}</b><span>Lowongan Aktif</span></article><article><b>{candidates.length}</b><span>Kandidat Ditampilkan</span></article><article><b>{candidates.filter(x => x.stage === "HIRED").length}</b><span>Diterima</span></article><article><b>{candidates.reduce((n, x) => n + x.tasks.filter(t => t.status !== "DONE").length, 0)}</b><span>Onboarding Belum Selesai</span></article></div>
    <form className="search-form" method="get"><input name="q" defaultValue={q} placeholder="Cari nama, email, atau telepon"/><select name="stage" defaultValue={stage}><option value="">Semua tahapan</option>{candidateStages.map(x => <option key={x} value={x}>{stageLabels[x]}</option>)}</select><select name="vacancyId" defaultValue={vacancyId}><option value="">Semua lowongan</option>{vacancies.map(x => <option key={x.id} value={x.id}>{x.title}</option>)}</select><button>Tampilkan</button></form>
    <div className="recruitment-create-grid">{canCreate && <details className="swap-panel"><summary>+ Buat Lowongan</summary><form action="/api/recruitment" method="post"><input type="hidden" name="action" value="CREATE_VACANCY"/><label>Kode<input name="code" required maxLength={40}/></label><label>Nama lowongan<input name="title" required maxLength={150}/></label><label>Departemen<select name="departmentId"><option value="">Belum ditentukan</option>{departments.map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Jabatan<select name="positionId"><option value="">Belum ditentukan</option>{positions.map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Kebutuhan<input name="openings" type="number" min="1" max="999" defaultValue="1"/></label><label>Batas lamaran<input name="deadline" type="date"/></label><label className="wide">Deskripsi<textarea name="notes" maxLength={1000}/></label><button>Buat Lowongan</button></form></details>}
      {canCreate && <details className="swap-panel"><summary>+ Tambah Kandidat</summary><form action="/api/recruitment" method="post"><input type="hidden" name="action" value="CREATE_CANDIDATE"/><label>Nama lengkap<input name="fullName" required maxLength={150}/></label><label>Lowongan<select name="vacancyId"><option value="">Umum / belum dipilih</option>{vacancies.filter(x => x.status !== "CLOSED").map(x => <option key={x.id} value={x.id}>{x.title}</option>)}</select></label><label>Email<input name="email" type="email"/></label><label>Telepon<input name="phone"/></label><label>NIK<input name="nationalId" inputMode="numeric"/></label><label>Tanggal lahir<input name="birthDate" type="date"/></label><label>Sumber kandidat<input name="source" placeholder="Referensi, Job Portal, dll"/></label><label className="wide">Alamat<textarea name="address"/></label><label className="wide">Catatan<textarea name="notes"/></label><button>Tambah Kandidat</button></form></details>}</div>
    <h2>Lowongan</h2><div className="vacancy-list">{vacancies.map(x => <article key={x.id}><div><b>{x.title}</b><small>{x.code} · {x.openings} kebutuhan · {x._count.candidates} kandidat</small></div><span className={`recruitment-badge stage-${x.status.toLowerCase()}`}>{x.status}</span>{canEdit && <form action="/api/recruitment" method="post"><input type="hidden" name="action" value="VACANCY_STATUS"/><input type="hidden" name="id" value={x.id}/><select name="status" defaultValue={x.status}><option>DRAFT</option><option>OPEN</option><option>CLOSED</option></select><button>Ubah</button></form>}{canDelete && <ConfirmRecruitmentForm action="/api/recruitment" method="post" message={`Nonaktifkan lowongan ${x.title}? Kandidat tidak ikut terhapus.`}><input type="hidden" name="action" value="DELETE_VACANCY"/><input type="hidden" name="id" value={x.id}/><button className="danger-button">Hapus</button></ConfirmRecruitmentForm>}</article>)}{!vacancies.length && <div className="empty-state">Belum ada lowongan.</div>}</div>
    <h2>Kandidat & Onboarding</h2><div className="candidate-list">{candidates.map(x => <details key={x.id}><summary><div><b>{x.fullName}</b><small>{x.vacancy?.title ?? "Kandidat umum"} · {x.email || x.phone || "Kontak belum diisi"}</small></div><span className={`recruitment-badge stage-${x.stage.toLowerCase()}`}>{stageLabels[x.stage as keyof typeof stageLabels] ?? x.stage}</span></summary><div className="candidate-body">
      {canEdit && !x.employeeId && <form className="inline-actions" action="/api/recruitment" method="post"><input type="hidden" name="action" value="CANDIDATE_STAGE"/><input type="hidden" name="id" value={x.id}/><select name="stage" defaultValue={x.stage}>{candidateStages.filter(s => s !== "HIRED").map(s => <option key={s} value={s}>{stageLabels[s]}</option>)}</select><button>Pindah Tahap</button></form>}
      {canEdit && !x.employeeId && <details className="hire-panel"><summary>Terima sebagai Karyawan</summary><ConfirmRecruitmentForm action="/api/recruitment" method="post" message={`Terima ${x.fullName} menjadi karyawan?`}><input type="hidden" name="action" value="HIRE"/><input type="hidden" name="id" value={x.id}/><label>ID Karyawan<input name="employeeNumber" required/></label><label>Tanggal masuk<input name="joinDate" type="date" required/></label><label>Cabang<select name="branchId"><option value="">Belum dipilih</option>{branches.map(b => <option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label>Departemen<select name="departmentId"><option value="">Belum dipilih</option>{departments.map(d => <option key={d.id} value={d.id}>{d.name}</option>)}</select></label><label>Jabatan<select name="positionId"><option value="">Belum dipilih</option>{positions.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Jenis kerja<select name="employmentType"><option value="">Belum dipilih</option><option value="PERMANENT">Tetap</option><option value="CONTRACT">Kontrak</option><option value="INTERNSHIP">Magang</option><option value="FREELANCE">Freelance</option><option value="PART_TIME">Paruh Waktu</option></select></label><button>Terima & Buat Karyawan</button></ConfirmRecruitmentForm></details>}
      {x.employee && <p className="form-success">Sudah menjadi karyawan: <a href={`/employees/${x.employee.id}`}>{x.employee.employeeNumber}</a></p>}
      <section><h3>Dokumen Kandidat</h3>{x.documents.map(d => <div className="candidate-row" key={d.id}><a href={`/api/recruitment/documents/${d.id}`}>{d.title}</a><small>{d.fileName}</small>{canEdit && <ConfirmRecruitmentForm action="/api/recruitment/documents" method="post" message={`Hapus dokumen ${d.title}?`}><input type="hidden" name="action" value="DELETE"/><input type="hidden" name="candidateId" value={x.id}/><input type="hidden" name="id" value={d.id}/><button className="danger-button">Hapus</button></ConfirmRecruitmentForm>}</div>)}{canEdit && <form action="/api/recruitment/documents" method="post" encType="multipart/form-data"><input type="hidden" name="candidateId" value={x.id}/><input name="title" placeholder="Judul dokumen" required/><input name="file" type="file" accept=".pdf,.jpg,.jpeg,.png" required/><button>Upload</button></form>}</section>
      <section><h3>Checklist Onboarding</h3>{x.tasks.map(t => <div className="candidate-row" key={t.id}><span className={t.status === "DONE" ? "task-done" : ""}>{t.title}</span><small>{t.dueDate?.toISOString().slice(0, 10) ?? "Tanpa batas waktu"}</small>{canEdit && <form action="/api/recruitment/tasks" method="post"><input type="hidden" name="action" value="TOGGLE"/><input type="hidden" name="id" value={t.id}/><button>{t.status === "DONE" ? "Buka Lagi" : "Selesai"}</button></form>}{canDelete && <ConfirmRecruitmentForm action="/api/recruitment/tasks" method="post" message={`Hapus tugas ${t.title}?`}><input type="hidden" name="action" value="DELETE"/><input type="hidden" name="id" value={t.id}/><button className="danger-button">Hapus</button></ConfirmRecruitmentForm>}</div>)}{canCreate && <form action="/api/recruitment/tasks" method="post"><input type="hidden" name="action" value="CREATE"/><input type="hidden" name="candidateId" value={x.id}/><input name="title" placeholder="Tambah tugas onboarding" required/><input name="dueDate" type="date"/><button>Tambah</button></form>}</section>
      {canDelete && !x.employeeId && <ConfirmRecruitmentForm action="/api/recruitment" method="post" message={`Hapus kandidat ${x.fullName}? Data akan dinonaktifkan dan audit tetap tersimpan.`}><input type="hidden" name="action" value="DELETE_CANDIDATE"/><input type="hidden" name="id" value={x.id}/><button className="danger-button">Hapus Kandidat</button></ConfirmRecruitmentForm>}
    </div></details>)}{!candidates.length && <div className="empty-state">Belum ada kandidat untuk filter ini.</div>}</div>
  </section></main>;
}
