"use client";
import { useState } from "react";
import { employeeFields } from "@/lib/excel";

type Preview = { filename: string; headers: string[]; rows: Record<string, unknown>[]; suggestedMapping: Record<string, string> };
export function EmployeeImportDialog() {
  const [open, setOpen] = useState(false), [step, setStep] = useState(1), [data, setData] = useState<Preview | null>(null), [mapping, setMapping] = useState<Record<string, string>>({}), [validation, setValidation] = useState<{ rows: Record<string, unknown>[]; summary: Record<string, number> } | null>(null), [busy, setBusy] = useState(false), [result, setResult] = useState<Record<string, unknown> | null>(null), [strategy, setStrategy] = useState("SKIP"), [createMasters, setCreateMasters] = useState(false);
  async function upload(file: File) { setBusy(true); const body = new FormData(); body.set("file", file); const response = await fetch("/api/employees/import/preview", { method: "POST", body }); const json = await response.json(); setBusy(false); if (!response.ok) return alert(json.error); setData(json); setMapping(json.suggestedMapping); setStep(2); }
  async function validate(dryRun: boolean) { if (!data) return; setBusy(true); const response = await fetch("/api/employees/import/commit", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ filename: data.filename, rows: data.rows, mapping, dryRun, duplicateStrategy: strategy, createMasters }) }); const json = await response.json(); setBusy(false); if (!response.ok) return alert(json.error); if (dryRun) { setValidation(json); setStep(3); } else { setResult(json); setStep(5); } }
  return <><button type="button" onClick={() => setOpen(true)}>Import Excel</button>{open && <div className="modal-backdrop"><section className="import-dialog"><header><div><b>Import Karyawan</b><small>Upload → Mapping → Preview → Konfirmasi → Hasil</small></div><button onClick={() => setOpen(false)}>×</button></header><div className="import-steps">{[1,2,3,4,5].map(number => <span className={step >= number ? "active" : ""} key={number}>{number}</span>)}</div>
  {step === 1 && <div className="import-stage"><h3>Upload file Excel</h3><p>XLSX atau XLS, maksimal 10 MB dan 5.000 baris.</p><input type="file" accept=".xlsx,.xls" disabled={busy} onChange={event => event.target.files?.[0] && void upload(event.target.files[0])}/></div>}
  {step === 2 && data && <div className="import-stage"><h3>Mapping Kolom</h3><div className="mapping-grid">{employeeFields.map(([field,label]) => <label key={field}>{label}{field === "fullName" && " *"}<select value={mapping[field] ?? ""} onChange={event => setMapping({...mapping,[field]:event.target.value})}><option value="">Tidak digunakan</option>{data.headers.map(header => <option key={header}>{header}</option>)}</select></label>)}</div><div className="import-options"><label><input type="checkbox" checked={createMasters} onChange={e => setCreateMasters(e.target.checked)}/> Buat Jabatan, Divisi, dan Cabang baru jika belum tersedia</label><label>Duplikat<select value={strategy} onChange={e => setStrategy(e.target.value)}><option value="SKIP">Lewati (paling aman)</option><option value="UPDATE">Update data lama</option><option value="NEW">Import sebagai baru</option></select></label></div><button disabled={!mapping.fullName || busy} onClick={() => void validate(true)}>Validasi & Preview</button></div>}
  {step === 3 && validation && <div className="import-stage"><h3>{validation.summary.total} baris terdeteksi</h3><div className="preview-summary">{Object.entries(validation.summary).map(([name,total]) => <b key={name}>{name}<span>{total}</span></b>)}</div><div className="preview-table">{validation.rows.slice(0,100).map((row,index) => <div key={index}><span>{String(row.row)}</span><strong>{String(row.name || "-")}</strong><b className={`row-${String(row.status).toLowerCase()}`}>{String(row.status)}</b><small>{[...(row.errors as string[]),...(row.warnings as string[])].join("; ")}</small></div>)}</div><button onClick={() => setStep(2)}>Kembali</button><button onClick={() => setStep(4)}>Lanjut Konfirmasi</button></div>}
  {step === 4 && validation && <div className="import-stage confirm-import"><h3>Konfirmasi Import</h3><p>Data baru/valid: <b>{(validation.summary.valid||0)+(validation.summary.warning||0)}</b></p><p>Data update: <b>{validation.summary.update||0}</b></p><p>Dilewati/error: <b>{(validation.summary.duplicate||0)+(validation.summary.error||0)}</b></p><button onClick={() => setStep(3)}>Batal</button><button disabled={busy} onClick={() => void validate(false)}>{busy ? "Mengimport..." : "Konfirmasi Import"}</button></div>}
  {step === 5 && result && <div className="import-stage"><h3>Import Selesai</h3><div className="preview-summary"><b>Baru<span>{String(result.created)}</span></b><b>Update<span>{String(result.updated)}</span></b><b>Skip<span>{String(result.skipped)}</span></b></div><a href="/employees">Lihat Karyawan</a></div>}</section></div>}</>;
}
