"use client";
import { useMemo, useState } from "react";
import { EmployeeDeleteForm } from "./EmployeeDeleteForm";
type Employee = { id: string; employeeNumber: string; fullName: string; email: string | null; employmentStatus: string; branch: { name: string } | null; department: { name: string } | null; position: { name: string } | null };
type Option = { id: string; name: string };
type Action = "STATUS" | "POSITION" | "DEPARTMENT" | "BRANCH" | "DELETE";
export function EmployeeBulkTable({ employees, branches, departments, positions, canEdit, canDelete, canExport }: { employees: Employee[]; branches: Option[]; departments: Option[]; positions: Option[]; canEdit: boolean; canDelete: boolean; canExport: boolean }) {
  const [selected, setSelected] = useState<string[]>([]), [action, setAction] = useState<Action>("STATUS"), [value, setValue] = useState("ACTIVE"), [busy, setBusy] = useState(false);
  const allSelected = employees.length > 0 && selected.length === employees.length;
  const options = useMemo(() => action === "POSITION" ? positions : action === "DEPARTMENT" ? departments : action === "BRANCH" ? branches : [], [action, positions, departments, branches]);
  function changeAction(next: Action) { setAction(next); setValue(next === "STATUS" ? "ACTIVE" : ""); }
  function toggle(id: string) { setSelected(current => current.includes(id) ? current.filter(item => item !== id) : [...current, id]); }
  async function apply() {
    if (!selected.length) return alert("Pilih minimal satu karyawan.");
    if (action !== "DELETE" && !value) return alert("Pilih perubahan yang akan diterapkan.");
    if (!window.confirm(`Yakin ingin ${action === "DELETE" ? "menonaktifkan" : "mengubah"} ${selected.length} karyawan terpilih?`)) return;
    setBusy(true); const response = await fetch("/api/employees/bulk", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ employeeIds: selected, action, value }) }); const json = await response.json(); setBusy(false);
    if (!response.ok) return alert(json.error); location.href = action === "DELETE" ? "/employees?deleted=bulk" : "/employees?saved=bulk";
  }
  function exportSelected() { if (!selected.length) return alert("Pilih minimal satu karyawan."); location.href = `/api/employees/export?ids=${encodeURIComponent(selected.join(","))}`; }
  return <>{(canEdit || canDelete || canExport) && <div className="employee-bulk-bar"><b>{selected.length} dipilih</b>{canEdit && <><select value={action} onChange={event => changeAction(event.target.value as Action)}><option value="STATUS">Ubah Status</option><option value="POSITION">Ubah Jabatan</option><option value="DEPARTMENT">Ubah Departemen</option><option value="BRANCH">Ubah Cabang</option>{canDelete && <option value="DELETE">Hapus/Nonaktifkan</option>}</select>{action === "STATUS" && <select value={value} onChange={event => setValue(event.target.value)}><option value="ACTIVE">Aktif</option><option value="INACTIVE">Nonaktif</option><option value="RESIGNED">Resign</option><option value="TERMINATED">PHK</option></select>}{["POSITION", "DEPARTMENT", "BRANCH"].includes(action) && <select value={value} onChange={event => setValue(event.target.value)}><option value="">Pilih tujuan...</option>{options.map(option => <option key={option.id} value={option.id}>{option.name}</option>)}</select>}{action === "DELETE" && <span className="danger-text">Karyawan dinonaktifkan, bukan dihapus permanen.</span>}<button disabled={busy || !selected.length} className={action === "DELETE" ? "danger-button" : ""} onClick={() => void apply()}>{busy ? "Memproses..." : "Terapkan"}</button></>}{canExport && <button disabled={!selected.length} onClick={exportSelected}>Export Terpilih</button>}</div>}
    <div className="data-table"><div className="data-row employee employee-bulk-heading"><label><input type="checkbox" checked={allSelected} onChange={() => setSelected(allSelected ? [] : employees.map(item => item.id))} aria-label="Pilih semua karyawan"/></label><b>NIK</b><b>Nama</b><b>Cabang</b><b>Departemen</b><b>Jabatan</b><b>Status</b></div>{employees.map(employee => <div className="employee-list-item employee-bulk-item" key={employee.id}><label className="employee-checkbox"><input type="checkbox" checked={selected.includes(employee.id)} onChange={() => toggle(employee.id)} aria-label={`Pilih ${employee.fullName}`}/></label><a href={`/employees/${employee.id}`} className="data-row employee employee-link"><strong>{employee.employeeNumber}</strong><span>{employee.fullName}<small>{employee.email ?? ""}</small></span><span>{employee.branch?.name ?? "-"}</span><span>{employee.department?.name ?? "-"}</span><span>{employee.position?.name ?? "-"}</span><span>{employee.employmentStatus}</span></a>{canDelete && <EmployeeDeleteForm employeeId={employee.id} employeeName={employee.fullName}/>}</div>)}</div></>;
}
