import { Prisma } from "@prisma/client";
import { requirePermission } from "@/lib/authorization";
import { db } from "@/lib/db";
import { hasPermission } from "@/lib/permissions";
import { redirect } from "next/navigation";
import { EmployeeImportDialog } from "./EmployeeImportDialog";
import { EmployeeBulkTable } from "./EmployeeBulkTable";
import { QuickAddSelect } from "./QuickAddSelect";
import { MasterQuickAddSelect } from "./MasterQuickAddSelect";

type EmployeeQuery = { saved?: string; deleted?: string; error?: string; q?: string; status?: string; positionId?: string; departmentId?: string; branchId?: string; religion?: string; maritalStatus?: string; contractType?: string; joinYear?: string; joinMonth?: string };
const months = ["Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember"];

export default async function EmployeesPage({ searchParams }: { searchParams: Promise<EmployeeQuery> }) {
  let tenant; try { tenant = await requirePermission("employees", "view"); } catch { redirect("/dashboard"); }
  const query = await searchParams, search = query.q?.trim(), year = Number(query.joinYear), month = Number(query.joinMonth);
  const joinDate = Number.isInteger(year) && year >= 1900 && year <= 2200 ? { gte: new Date(Date.UTC(year, month >= 1 && month <= 12 ? month - 1 : 0, 1)), lt: new Date(Date.UTC(month >= 1 && month <= 12 ? year : year + 1, month >= 1 && month <= 12 ? month : 0, 1)) } : undefined;
  const where: Prisma.EmployeeWhereInput = { companyId: tenant.companyId, deletedAt: null, ...(search ? { OR: [{ fullName: { contains: search, mode: "insensitive" } }, { employeeNumber: { contains: search, mode: "insensitive" } }, { nationalId: { contains: search } }, { phone: { contains: search } }, { email: { contains: search, mode: "insensitive" } }] } : {}), ...(query.status ? { employmentStatus: query.status as "ACTIVE"|"INACTIVE"|"RESIGNED"|"TERMINATED" } : {}), ...(query.positionId ? { positionId: query.positionId } : {}), ...(query.departmentId ? { departmentId: query.departmentId } : {}), ...(query.branchId ? { branchId: query.branchId } : {}), ...(query.religion ? { religion: { equals: query.religion, mode: "insensitive" } } : {}), ...(query.maritalStatus ? { maritalStatus: { equals: query.maritalStatus, mode: "insensitive" } } : {}), ...(query.contractType ? { contractTypeLabel: { equals: query.contractType, mode: "insensitive" } } : {}), ...(joinDate ? { joinDate } : {}) };
  const [employees, branches, departments, positions, masterOptions] = await Promise.all([
    db.employee.findMany({ where, select: { id: true, employeeNumber: true, fullName: true, email: true, employmentStatus: true, branch: { select: { name: true } }, department: { select: { name: true } }, position: { select: { name: true } } }, orderBy: [{ department: { name: "asc" } }, { position: { name: "asc" } }, { fullName: "asc" }], take: 500 }),
    db.branch.findMany({ where: { companyId: tenant.companyId, deletedAt: null }, orderBy: { name: "asc" } }),
    db.department.findMany({ where: { companyId: tenant.companyId, deletedAt: null }, orderBy: { name: "asc" } }),
    db.position.findMany({ where: { companyId: tenant.companyId, deletedAt: null }, orderBy: { name: "asc" } }),
    db.masterData.findMany({ where: { companyId: tenant.companyId, category: { in: ["CONTRACT_TYPE", "RELIGION", "MARITAL_STATUS"] }, isActive: true, deletedAt: null }, select: { id: true, name: true, category: true }, orderBy: [{ sortOrder: "asc" }, { name: "asc" }] }),
  ]);
  const contractTypes = masterOptions.filter(item => item.category === "CONTRACT_TYPE"), religions = masterOptions.filter(item => item.category === "RELIGION"), maritalStatuses = masterOptions.filter(item => item.category === "MARITAL_STATUS");
  const exportQuery = new URLSearchParams(Object.entries(query).filter(([key, value]) => value && !["saved", "deleted", "error"].includes(key)) as string[][]).toString(), permissions = tenant.membership.role.permissions;
  return <main className="settings-page"><section className="settings-card"><header><div><span className="eyebrow">PANBOY HR</span><h1>Data karyawan</h1><p>{employees.length} data ditampilkan dari {tenant.membership.company.name}.</p></div><a href="/dashboard">Kembali</a></header>
    {query.saved && <div className="form-success">Karyawan berhasil disimpan.</div>}{query.deleted && <div className="form-success">Karyawan berhasil dinonaktifkan.</div>}{query.error && <div className="form-error">Data gagal diproses. Periksa isian dan izin Anda.</div>}
    <form className="employee-filter-form"><input name="q" defaultValue={search} placeholder="Cari nama, ID, NIK, telepon, email"/><select name="status" defaultValue={query.status??""}><option value="">Semua status</option><option value="ACTIVE">Aktif</option><option value="INACTIVE">Nonaktif</option><option value="RESIGNED">Resign</option><option value="TERMINATED">PHK</option></select><select name="positionId" defaultValue={query.positionId??""}><option value="">Semua jabatan</option>{positions.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select><select name="departmentId" defaultValue={query.departmentId??""}><option value="">Semua departemen</option>{departments.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select><select name="branchId" defaultValue={query.branchId??""}><option value="">Semua cabang</option>{branches.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select><select name="contractType" defaultValue={query.contractType??""}><option value="">Semua jenis kontrak</option>{contractTypes.map(item=><option key={item.id} value={item.name}>{item.name}</option>)}</select><select name="religion" defaultValue={query.religion??""}><option value="">Semua agama</option>{religions.map(item=><option key={item.id} value={item.name}>{item.name}</option>)}</select><select name="maritalStatus" defaultValue={query.maritalStatus??""}><option value="">Semua status pernikahan</option>{maritalStatuses.map(item=><option key={item.id} value={item.name}>{item.name}</option>)}</select><input name="joinYear" type="number" min="1900" max="2200" defaultValue={query.joinYear} placeholder="Tahun masuk"/><select name="joinMonth" defaultValue={query.joinMonth??""}><option value="">Semua bulan</option>{months.map((name,index)=><option key={name} value={index+1}>{name}</option>)}</select><button>Terapkan Filter</button><a className="secondary-button" href="/employees">Reset</a></form>
    <div className="standard-toolbar"><div className="toolbar-actions">{hasPermission(permissions, "employees", "create") && <><a href="#tambah-karyawan">+ Tambah</a><EmployeeImportDialog/></>}{hasPermission(permissions, "employees", "export") && <><a href="/api/employees/export">Export Semua</a><a href={`/api/employees/export${exportQuery ? `?${exportQuery}` : ""}`}>Export Hasil Filter</a></>}<a href="/api/employees/template">Download Template</a><a href="/employees/imports">Riwayat Import</a></div></div>
    <EmployeeBulkTable employees={employees} branches={branches.map(({id,name})=>({id,name}))} departments={departments.map(({id,name})=>({id,name}))} positions={positions.map(({id,name})=>({id,name}))} canEdit={hasPermission(permissions,"employees","edit")} canDelete={hasPermission(permissions,"employees","delete")} canExport={hasPermission(permissions,"employees","export")}/>
    {hasPermission(permissions, "employees", "create") && <form id="tambah-karyawan" className="settings-form employee-form" action="/api/employees" method="post"><h2 className="wide">Tambah karyawan</h2><label>NIK internal<input name="employeeNumber" required/></label><label>Nama lengkap<input name="fullName" required/></label><label>Email<input name="email" type="email"/></label><label>Nomor HP<input name="phone"/></label><label>Tanggal bergabung<input name="joinDate" type="date" required/></label><MasterQuickAddSelect label="Jenis Kontrak" category="CONTRACT_TYPE" fieldName="contractTypeLabel" options={contractTypes} canAdd={hasPermission(permissions,"master_data","create")||hasPermission(permissions,"employees","edit")}/><QuickAddSelect kind="branch" fieldName="branchId" options={branches.map(({id,name})=>({id,name}))} canAdd={hasPermission(permissions,"branches","create")}/><QuickAddSelect kind="department" fieldName="departmentId" options={departments.map(({id,name})=>({id,name}))} canAdd={hasPermission(permissions,"departments","create")}/><QuickAddSelect kind="position" fieldName="positionId" options={positions.map(({id,name})=>({id,name}))} canAdd={hasPermission(permissions,"positions","create")}/><label>Libur per bulan<input name="monthlyDaysOff" type="number" min="0" max="31" defaultValue="4" required/></label><button className="wide" type="submit">Tambah karyawan</button></form>}
  </section></main>;
}
