import { requirePermission } from "@/lib/authorization";
import { db } from "@/lib/db";
import { hasPermission } from "@/lib/permissions";
import { notFound, redirect } from "next/navigation";

const iso = (date: Date | null) => date?.toISOString().slice(0, 10) ?? "";
export default async function EmployeeDetail({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ saved?: string; error?: string }> }) {
  let tenant; try { tenant = await requirePermission("employees", "view"); } catch { redirect("/dashboard"); }
  const { id } = await params;
  const [employee, branches, departments, positions, history] = await Promise.all([
    db.employee.findFirst({ where: { id, companyId: tenant.companyId, deletedAt: null }, include: { branch: true, department: true, position: true } }),
    db.branch.findMany({ where: { companyId: tenant.companyId, deletedAt: null } }), db.department.findMany({ where: { companyId: tenant.companyId, deletedAt: null } }), db.position.findMany({ where: { companyId: tenant.companyId, deletedAt: null } }),
    db.auditLog.findMany({ where: { companyId: tenant.companyId, entityType: "Employee", entityId: id }, include: { actor: { select: { fullName: true } } }, orderBy: { createdAt: "desc" }, take: 30 }),
  ]);
  if (!employee) notFound(); const message = await searchParams, editable = hasPermission(tenant.membership.role.permissions, "employees", "edit");
  return <main className="settings-page"><section className="settings-card"><header><div><span className="eyebrow">KARYAWAN · {employee.employeeNumber}</span><h1>{employee.fullName}</h1><p>{employee.position?.name ?? "Tanpa jabatan"} · {employee.department?.name ?? "Tanpa departemen"}</p></div><a href="/employees">Kembali</a></header>
    {message.saved && <div className="form-success">Data karyawan berhasil diperbarui.</div>}{message.error && <div className="form-error">Perubahan gagal disimpan.</div>}
    <form className="settings-form employee-form employee-profile-form" action="/api/employees/update" method="post"><input type="hidden" name="employeeId" value={employee.id}/>
      <h2 className="wide">A. Informasi Utama</h2><label>Nama lengkap<input name="fullName" defaultValue={employee.fullName} required disabled={!editable}/></label><label>Status keaktifan<input name="employeeStatusLabel" defaultValue={employee.employeeStatusLabel ?? employee.employmentStatus} disabled={!editable}/></label><label>Cabang<select name="branchId" defaultValue={employee.branchId ?? ""} disabled={!editable}><option value="">Tanpa cabang</option>{branches.map(item => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label>Departemen<select name="departmentId" defaultValue={employee.departmentId ?? ""} disabled={!editable}><option value="">Tanpa departemen</option>{departments.map(item => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label>Jabatan<select name="positionId" defaultValue={employee.positionId ?? ""} disabled={!editable}><option value="">Tanpa jabatan</option>{positions.map(item => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label>Tanggal masuk<input name="joinDate" type="date" defaultValue={iso(employee.joinDate)} disabled={!editable}/></label>
      <h2 className="wide">B. Data Pribadi</h2><label>Tempat lahir<input name="placeOfBirth" defaultValue={employee.placeOfBirth ?? ""} disabled={!editable}/></label><label>Tanggal lahir<input name="birthDate" type="date" defaultValue={iso(employee.birthDate)} disabled={!editable}/></label><label>Agama<input name="religion" defaultValue={employee.religion ?? ""} disabled={!editable}/></label><label>Status pernikahan<input name="maritalStatus" defaultValue={employee.maritalStatus ?? ""} disabled={!editable}/></label><label className="wide">Alamat<textarea name="address" defaultValue={employee.address ?? ""} disabled={!editable}/></label>
      <h2 className="wide">C. Kontak</h2><label>Nomor telepon<input name="phone" defaultValue={employee.phone ?? ""} disabled={!editable}/></label><label>Nomor telepon tambahan<input name="additionalPhone" defaultValue={employee.additionalPhone ?? ""} disabled={!editable}/></label><label>Email<input name="email" type="email" defaultValue={employee.email ?? ""} disabled={!editable}/></label>
      <h2 className="wide">D. Identitas</h2><label>NIK / No KTP<input name="nationalId" defaultValue={employee.nationalId ?? ""} disabled={!editable}/></label><label>No KK<input name="familyCardNumber" defaultValue={employee.familyCardNumber ?? ""} disabled={!editable}/></label><label>NPWP<input name="taxNumber" defaultValue={employee.taxNumber ?? ""} disabled={!editable}/></label>
      <h2 className="wide">E. Kepegawaian</h2><label>Jenis kerja<select name="employmentType" defaultValue={employee.employmentType ?? "CONTRACT"} disabled={!editable}><option value="PERMANENT">Tetap</option><option value="CONTRACT">Kontrak</option><option value="INTERNSHIP">Magang</option><option value="FREELANCE">Freelance</option><option value="PART_TIME">Paruh waktu</option></select></label><label>Status sistem<select name="employmentStatus" defaultValue={employee.employmentStatus} disabled={!editable}><option>ACTIVE</option><option>INACTIVE</option><option>RESIGNED</option><option>TERMINATED</option></select></label><label>Mulai kontrak<input name="contractStartDate" type="date" defaultValue={iso(employee.contractStartDate)} disabled={!editable}/></label><label>Berakhir kontrak<input name="contractEndDate" type="date" defaultValue={iso(employee.contractEndDate)} disabled={!editable}/></label><label>Tanggal berhenti<input name="stopDate" type="date" defaultValue={iso(employee.stopDate)} disabled={!editable}/></label><label>Alasan berhenti<input name="terminationReason" defaultValue={employee.terminationReason ?? ""} disabled={!editable}/></label><label>Libur per bulan<input name="monthlyDaysOff" type="number" min="0" max="31" defaultValue={employee.monthlyDaysOff} disabled={!editable}/></label>
      <h2 className="wide">F. Bank & Payroll</h2><label>Nama bank<input name="bankName" defaultValue={employee.bankName ?? ""} disabled={!editable}/></label><label>No rekening<input name="bankAccountNumber" defaultValue={employee.bankAccountNumber ?? ""} disabled={!editable}/></label><label>Atas nama<input name="bankAccountHolder" defaultValue={employee.bankAccountHolder ?? ""} disabled={!editable}/></label><label>BPJS Kesehatan<input name="bpjsHealth" defaultValue={employee.bpjsHealth ?? ""} disabled={!editable}/></label><label>BPJS Ketenagakerjaan<input name="bpjsEmployment" defaultValue={employee.bpjsEmployment ?? ""} disabled={!editable}/></label>
      {editable && <button className="wide">Simpan perubahan</button>}
    </form>
    <h2>Riwayat perubahan</h2><div className="timeline">{history.map(item => <article key={item.id}><span>{item.createdAt.toLocaleString("id-ID")}</span><strong>{item.action}</strong><p>{item.actor?.fullName ?? "System"}</p></article>)}{history.length === 0 && <p>Belum ada riwayat.</p>}</div>
  </section></main>;
}
