import { db } from "@/lib/db";
import { requireSuperAdmin } from "@/lib/platform";
import { redirect } from "next/navigation";

type Query = { status?: string; email?: string; from?: string; to?: string };

export default async function LoginHistoryPage({ searchParams }: { searchParams: Promise<Query> }) {
  try { await requireSuperAdmin(); } catch { redirect("/login"); }
  const query = await searchParams, since = new Date(Date.now() - 24 * 60 * 60 * 1000);
  const where = { ...(query.status === "success" ? { success: true } : query.status === "failed" ? { success: false } : {}), ...(query.email ? { user: { email: { contains: query.email, mode: "insensitive" as const } } } : {}), ...((query.from || query.to) ? { createdAt: { ...(query.from ? { gte: new Date(`${query.from}T00:00:00.000Z`) } : {}), ...(query.to ? { lte: new Date(`${query.to}T23:59:59.999Z`) } : {}) } } : {}) };
  const [histories, success24h, failed24h] = await Promise.all([db.loginHistory.findMany({ where, include: { user: { select: { fullName: true, email: true } } }, orderBy: { createdAt: "desc" }, take: 200 }), db.loginHistory.count({ where: { success: true, createdAt: { gte: since } } }), db.loginHistory.count({ where: { success: false, createdAt: { gte: since } } })]);
  const exportQuery = new URLSearchParams(Object.entries(query).filter((entry): entry is [string, string] => Boolean(entry[1]))).toString();
  return <main className="settings-page"><section className="settings-card"><header><div><span className="eyebrow">SUPER ADMIN</span><h1>Riwayat login</h1><p>Pantau login berhasil dan gagal untuk mendeteksi aktivitas akun.</p></div><a href="/platform">Kembali</a></header><div className="security-summary"><article><span>Berhasil 24 jam</span><strong>{success24h}</strong></article><article><span>Gagal 24 jam</span><strong className={failed24h ? "danger-text" : "success-text"}>{failed24h}</strong></article><article><span>Data ditampilkan</span><strong>{histories.length}</strong></article></div><form className="platform-filter" method="get"><input name="email" type="search" placeholder="Cari email" defaultValue={query.email ?? ""}/><select name="status" defaultValue={query.status ?? ""}><option value="">Semua status</option><option value="success">Berhasil</option><option value="failed">Gagal</option></select><input type="date" name="from" defaultValue={query.from ?? ""}/><input type="date" name="to" defaultValue={query.to ?? ""}/><button type="submit">Tampilkan</button><a href="/platform/logins">Reset</a><a href={`/api/platform/logins/export${exportQuery ? `?${exportQuery}` : ""}`}>Export Excel</a></form><div className="data-table"><div className="data-row login heading"><b>Waktu</b><b>User</b><b>Status</b><b>IP</b></div>{histories.map(item => <div className="data-row login" key={item.id}><span>{item.createdAt.toLocaleString("id-ID")}</span><span>{item.user.fullName}<small>{item.user.email}</small></span><strong className={item.success ? "success-text" : "danger-text"}>{item.success ? "Berhasil" : "Gagal"}</strong><span>{item.ipAddress ?? "-"}</span></div>)}</div></section></main>;
}
