import { db } from "@/lib/db";
import { requireSuperAdmin } from "@/lib/platform";
import { redirect } from "next/navigation";
import { CompanyDeleteForm } from "./CompanyDeleteForm";

export default async function PlatformDashboard({ searchParams }: { searchParams: Promise<{ saved?: string; clientSaved?: string; error?: string; status?: string; deleted?: string }> }) {
  try { await requireSuperAdmin(); } catch { redirect("/login"); }
  const companies = await db.company.findMany({ where: { deletedAt: null }, include: { _count: { select: { employees: true } }, memberships: { where: { status: "ACTIVE", role: { name: "Owner" } }, include: { user: true }, take: 1 } }, orderBy: { name: "asc" } });
  const message = await searchParams;
  return <main className="platform-page"><section className="platform-card"><header><div><span className="eyebrow">SUPER ADMIN PLATFORM</span><h1>Semua perusahaan</h1><p>Statistik dipisahkan per tenant dan tidak menggabungkan data operasional.</p></div><form action="/api/auth/logout" method="post"><button>Keluar</button></form></header>
    {message.saved && <div className="form-success">Perusahaan {message.saved} dan akun client berhasil dibuat.</div>}{message.clientSaved && <div className="form-success">Akun client berhasil diperbarui.</div>}{message.deleted && <div className="form-success">Perusahaan {message.deleted} berhasil dinonaktifkan dan disembunyikan. Datanya tidak dihapus permanen.</div>}{message.error && <div className="form-error">Operasi gagal. Periksa data atau coba kembali. Tidak ada data yang dihapus.</div>}
    <div className="platform-actions"><a href="/platform/audit">Audit platform</a><a href="/platform/logins">Riwayat login</a></div>
    <div className="company-list">{companies.map(company => { const owner = company.memberships[0]?.user; return <article key={company.id}><div><strong>{company.name}</strong><small>{company.code} · {company.status} · {company._count.employees} karyawan</small>{owner && <small>Client: {owner.email}</small>}</div><div className="company-actions">{company.status === "ACTIVE" && <form action="/api/platform/company-access" method="post"><input type="hidden" name="companyId" value={company.id}/><button type="submit">Kelola perusahaan</button></form>}<form action="/api/platform/companies/status" method="post"><input type="hidden" name="companyId" value={company.id}/><select name="status" defaultValue={company.status}><option>ACTIVE</option><option>INACTIVE</option><option>SUSPENDED</option></select><button type="submit">Ubah status</button></form><CompanyDeleteForm companyId={company.id} companyName={company.name}/><form action="/api/platform/clients" method="post" className="client-account-form"><input type="hidden" name="companyId" value={company.id}/><input name="fullName" defaultValue={owner?.fullName ?? "Owner"} placeholder="Nama client" required/><input name="email" type="email" defaultValue={owner?.email ?? ""} placeholder="Email login client" required/><input name="password" type="password" minLength={8} placeholder={owner ? "Password baru (opsional)" : "Password awal minimal 8 karakter"} required={!owner}/><button type="submit">{owner ? "Perbarui akun client" : "Buat akun client"}</button></form></div></article>})}</div>
    <form action="/api/platform/companies" method="post" className="create-company"><h2>Tambah perusahaan + akun client</h2><div><label>Kode<input name="code" placeholder="CONTOH_ID" required /></label><label>Nama perusahaan<input name="name" required /></label><label>Nama client/Owner<input name="ownerName" required /></label><label>Email login client<input name="email" type="email" required /></label><label>Password awal<input name="password" type="password" minLength={8} required /></label><label>Zona waktu<select name="timezone" defaultValue="Asia/Makassar"><option>Asia/Jakarta</option><option>Asia/Makassar</option><option>Asia/Jayapura</option></select></label></div><button type="submit">Buat perusahaan dan akun client</button></form>
  </section></main>;
}
