import { requirePermission } from "@/lib/authorization";
import { db } from "@/lib/db";
import { styledSheet, workbookResponse } from "@/lib/excel";
import { NextRequest } from "next/server";
import * as XLSX from "xlsx";
import { Prisma } from "@prisma/client";

export async function GET(request: NextRequest) {
  try {
    const tenant = await requirePermission("employees", "export"), params = request.nextUrl.searchParams, q = params.get("q")?.trim(), status = params.get("status"), ids = params.get("ids")?.split(",").filter(Boolean).slice(0, 500), positionId = params.get("positionId"), departmentId = params.get("departmentId"), branchId = params.get("branchId"), religion = params.get("religion"), maritalStatus = params.get("maritalStatus"), contractType = params.get("contractType"), year = Number(params.get("joinYear")), month = Number(params.get("joinMonth"));
    const joinDate = Number.isInteger(year) && year >= 1900 && year <= 2200 ? { gte: new Date(Date.UTC(year, month >= 1 && month <= 12 ? month - 1 : 0, 1)), lt: new Date(Date.UTC(month >= 1 && month <= 12 ? year : year + 1, month >= 1 && month <= 12 ? month : 0, 1)) } : undefined;
    const where: Prisma.EmployeeWhereInput = { companyId: tenant.companyId, deletedAt: null, ...(ids?.length ? { id: { in: ids } } : {}), ...(q ? { OR: [{ fullName: { contains: q, mode: "insensitive" } }, { employeeNumber: { contains: q, mode: "insensitive" } }, { nationalId: { contains: q } }, { phone: { contains: q } }, { email: { contains: q, mode: "insensitive" } }] } : {}), ...(status && status !== "ALL" ? { employmentStatus: status as "ACTIVE" | "INACTIVE" | "RESIGNED" | "TERMINATED" } : {}), ...(positionId ? { positionId } : {}), ...(departmentId ? { departmentId } : {}), ...(branchId ? { branchId } : {}), ...(religion ? { religion: { equals: religion, mode: "insensitive" } } : {}), ...(maritalStatus ? { maritalStatus: { equals: maritalStatus, mode: "insensitive" } } : {}), ...(contractType ? { contractTypeLabel: { equals: contractType, mode: "insensitive" } } : {}), ...(joinDate ? { joinDate } : {}) };
    const employees = await db.employee.findMany({ where, include: { branch: true, department: true, position: true }, orderBy: [{ department: { name: "asc" } }, { position: { name: "asc" } }, { fullName: "asc" }] });
    const rows = [["Nama Karyawan", "ID Karyawan", "NIK / No KTP", "Jabatan", "Divisi / Departemen", "Nomor Telepon", "Email", "Tanggal Masuk", "Berakhir Kontrak", "Tanggal Berhenti", "Tempat Lahir", "Tanggal Lahir", "Alamat", "Status Keaktifan", "Status Pernikahan", "Agama", "Jenis Kontrak", "Cabang"], ...employees.map(item => [item.fullName, item.employeeNumber, item.nationalId ?? "", item.position?.name ?? "", item.department?.name ?? "", item.phone ?? "", item.email ?? "", item.joinDate?.toISOString().slice(0, 10) ?? "", item.contractEndDate?.toISOString().slice(0, 10) ?? "", item.stopDate?.toISOString().slice(0, 10) ?? "", item.placeOfBirth ?? "", item.birthDate?.toISOString().slice(0, 10) ?? "", item.address ?? "", item.employeeStatusLabel ?? item.employmentStatus, item.maritalStatus ?? "", item.religion ?? "", item.contractTypeLabel ?? item.employmentType ?? "", item.branch?.name ?? ""] )];
    const workbook = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(workbook, styledSheet(rows, [25, 18, 20, 22, 22, 24, 28, 16, 16, 16, 18, 16, 32, 18, 18, 18, 18, 22]), "Data Karyawan");
    await db.auditLog.create({ data: { companyId: tenant.companyId, actorUserId: tenant.session.userId, action: "EXPORT", module: "employees", newValue: { rows: employees.length, filtered: Boolean(q || status || ids?.length || positionId || departmentId || branchId || religion || maritalStatus || contractType || joinDate), selected: ids?.length ?? 0 } } });
    return workbookResponse(workbook, `data-karyawan-${new Date().toISOString().slice(0, 10)}.xlsx`);
  } catch { return new Response("Forbidden", { status: 403 }); }
}
