"use client";
import { useState } from "react";

type Kind = "branch" | "department" | "position";
type Row = { row: number; code: string; name: string; address: string; radiusM: number; timezone: string; isActive: boolean; status: "NEW" | "UPDATE" | "ERROR"; errors: string[] };
type Preview = { filename: string; kind: Kind; rows: Row[]; summary: { total: number; new: number; update: number; error: number } };

export function OrganizationImportDialog({ kind, title }: { kind: Kind; title: string }) {
  const [open, setOpen] = useState(false), [busy, setBusy] = useState(false), [preview, setPreview] = useState<Preview | null>(null), [result, setResult] = useState<{ created: number; updated: number } | null>(null);
  async function upload(file: File) { setBusy(true); const body = new FormData(); body.set("kind", kind); body.set("file", file); const response = await fetch("/api/organization/import/preview", { method: "POST", body }); const json = await response.json(); setBusy(false); if (!response.ok) return alert(json.error); setPreview(json); }
  async function commit() { if (!preview) return; setBusy(true); const rows = preview.rows.filter(row => row.status !== "ERROR").map(({ status, errors, row, ...data }) => data); const response = await fetch("/api/organization/import/commit", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ kind, filename: preview.filename, rows }) }); const json = await response.json(); setBusy(false); if (!response.ok) return alert(json.error); setResult(json); }
  function close() { setOpen(false); setPreview(null); setResult(null); if (result) location.href = "/organization?saved=import"; }
  return <><button type="button" onClick={() => setOpen(true)}>Import Excel</button>{open && <div className="modal-backdrop"><section className="import-dialog"><header><div><b>Import {title}</b><small>Upload → Preview → Konfirmasi → Hasil</small></div><button onClick={close}>×</button></header>{!preview && !result && <div className="import-stage"><h3>Upload Excel {title}</h3><p>Nama wajib. Kode boleh dikosongkan dan akan dibuat otomatis.</p><input type="file" accept=".xlsx,.xls" disabled={busy} onChange={event => event.target.files?.[0] && void upload(event.target.files[0])}/><a href={`/api/organization/template?kind=${kind}`}>Download Template</a></div>}{preview && !result && <div className="import-stage"><h3>Preview Import</h3><div className="preview-summary"><b>Total<span>{preview.summary.total}</span></b><b>Baru<span>{preview.summary.new}</span></b><b>Update<span>{preview.summary.update}</span></b><b>Error<span>{preview.summary.error}</span></b></div><div className="preview-table">{preview.rows.slice(0, 300).map(item => <div key={item.row}><span>{item.row}</span><strong>{item.code} — {item.name}</strong><b className={`row-${item.status.toLowerCase()}`}>{item.status}</b><small>{item.errors.join("; ")}</small></div>)}</div><p>Baris error dilewati. Data dengan kode atau nama yang sama akan diperbarui.</p><button onClick={() => setPreview(null)}>Ganti File</button><button disabled={busy || preview.summary.new + preview.summary.update === 0} onClick={() => void commit()}>{busy ? "Mengimport..." : `Konfirmasi ${preview.summary.new + preview.summary.update} Data`}</button></div>}{result && <div className="import-stage"><h3>Import Selesai</h3><div className="preview-summary"><b>Data Baru<span>{result.created}</span></b><b>Diupdate<span>{result.updated}</span></b></div><button onClick={close}>Lihat Struktur Organisasi</button></div>}</section></div>}</>;
}
