import { requirePermission } from "@/lib/authorization";
import { db } from "@/lib/db";
import { hasPermission } from "@/lib/permissions";
import { attendanceStatuses, completionStatuses, trainingStatuses } from "@/lib/training";
import { redirect } from "next/navigation";
import { ConfirmTrainingForm } from "./TrainingActions";

export default async function TrainingPage({ searchParams }: { searchParams: Promise<{ status?: string; q?: string; saved?: string; error?: string }> }) {
  let tenant; try { tenant = await requirePermission("training", "view"); } catch { redirect("/dashboard"); }
  const query = await searchParams, status = trainingStatuses.includes(query.status as never) ? query.status : "", q = query.q?.trim() ?? "";
  const [programs, employees] = await Promise.all([
    db.trainingProgram.findMany({ where: { companyId: tenant.companyId, deletedAt: null, ...(status ? { status } : {}), ...(q ? { OR: [{ name: { contains: q, mode: "insensitive" } }, { code: { contains: q, mode: "insensitive" } }, { provider: { contains: q, mode: "insensitive" } }] } : {}) }, include: { participants: { where: { deletedAt: null }, include: { employee: { include: { department: true, position: true } } }, orderBy: { employee: { fullName: "asc" } } } }, orderBy: { startDate: "desc" } }),
    db.employee.findMany({ where: { companyId: tenant.companyId, deletedAt: null, employmentStatus: "ACTIVE" }, select: { id: true, employeeNumber: true, fullName: true }, orderBy: { fullName: "asc" } }),
  ]);
  const permissions = tenant.membership.role.permissions, canCreate = hasPermission(permissions, "training", "create"), canEdit = hasPermission(permissions, "training", "edit"), canDelete = hasPermission(permissions, "training", "delete"), canExport = hasPermission(permissions, "training", "export");
  const participants = programs.flatMap(x => x.participants);
  return <main className="settings-page"><section className="settings-card training-page"><header><div><span className="eyebrow">PANBOY HR</span><h1>Pelatihan & Pengembangan</h1><p>Program, peserta, hasil, dan sertifikat khusus {tenant.membership.company.name}.</p></div><a href="/dashboard">Kembali</a></header>
    {query.saved && <div className="form-success">Data pelatihan berhasil diproses.</div>}{query.error && <div className="form-error">Operasi gagal ({query.error}). Periksa tanggal, kapasitas, duplikat peserta, dan hak akses.</div>}
    <div className="training-stats"><article><b>{programs.length}</b><span>Program</span></article><article><b>{participants.length}</b><span>Peserta</span></article><article><b>{participants.filter(x => x.attendanceStatus === "PRESENT").length}</b><span>Hadir</span></article><article><b>{participants.filter(x => x.completionStatus === "PASSED").length}</b><span>Lulus</span></article></div>
    <div className="standard-toolbar"><form className="search-form" method="get"><input name="q" defaultValue={q} placeholder="Cari kode, program, atau penyelenggara"/><select name="status" defaultValue={status}><option value="">Semua status</option>{trainingStatuses.map(x => <option key={x}>{x}</option>)}</select><button>Tampilkan</button></form>{canExport && <a className="generator-link-button" href="/api/training/export">Export Excel</a>}</div>
    {canCreate && <details className="swap-panel training-create"><summary>+ Buat Program Pelatihan</summary><form action="/api/training" method="post"><input type="hidden" name="action" value="CREATE_PROGRAM"/><label>Kode<input name="code" required/></label><label>Nama program<input name="name" required/></label><label>Kategori<input name="category" placeholder="Teknis, Leadership, Safety"/></label><label>Penyelenggara<input name="provider"/></label><label>Lokasi<input name="location"/></label><label>Tanggal mulai<input name="startDate" type="date" required/></label><label>Tanggal selesai<input name="endDate" type="date" required/></label><label>Kapasitas<input name="capacity" type="number" min="1"/></label><label>Biaya<input name="cost" type="number" min="0" step="0.01"/></label><label className="wide">Deskripsi<textarea name="description"/></label><button>Buat Program</button></form></details>}
    <div className="training-list">{programs.map(program => <details key={program.id}><summary><div><b>{program.name}</b><small>{program.code} · {program.startDate.toISOString().slice(0, 10)} s.d. {program.endDate.toISOString().slice(0, 10)} · {program.participants.length}/{program.capacity ?? "∞"} peserta</small></div><span className={`training-badge training-${program.status.toLowerCase()}`}>{program.status}</span></summary><div className="training-body">
      <div className="training-program-actions">{canEdit && <form action="/api/training" method="post"><input type="hidden" name="action" value="PROGRAM_STATUS"/><input type="hidden" name="id" value={program.id}/><select name="status" defaultValue={program.status}>{trainingStatuses.map(x => <option key={x}>{x}</option>)}</select><button>Ubah Status</button></form>}{canDelete && <ConfirmTrainingForm action="/api/training" method="post" message={`Nonaktifkan program ${program.name}? Riwayat audit tetap disimpan.`}><input type="hidden" name="action" value="DELETE_PROGRAM"/><input type="hidden" name="id" value={program.id}/><button className="danger-button">Hapus Program</button></ConfirmTrainingForm>}</div>
      {canCreate && <form className="add-participant" action="/api/training" method="post"><input type="hidden" name="action" value="ADD_PARTICIPANT"/><input type="hidden" name="trainingProgramId" value={program.id}/><select name="employeeId" required><option value="">Pilih karyawan</option>{employees.map(x => <option key={x.id} value={x.id}>{x.employeeNumber} · {x.fullName}</option>)}</select><button>Tambah Peserta</button></form>}
      <div className="training-participants">{program.participants.map(item => <article key={item.id}><div><b>{item.employee.fullName}</b><small>{item.employee.employeeNumber} · {item.employee.department?.name ?? "Tanpa departemen"} · {item.employee.position?.name ?? "Tanpa jabatan"}</small></div>{canEdit ? <form action="/api/training" method="post"><input type="hidden" name="action" value="UPDATE_PARTICIPANT"/><input type="hidden" name="id" value={item.id}/><select name="attendanceStatus" defaultValue={item.attendanceStatus}>{attendanceStatuses.map(x => <option key={x}>{x}</option>)}</select><select name="completionStatus" defaultValue={item.completionStatus}>{completionStatuses.map(x => <option key={x}>{x}</option>)}</select><input name="score" type="number" min="0" max="100" defaultValue={item.score ?? ""} placeholder="Nilai"/><input name="certificateNumber" defaultValue={item.certificateNumber ?? ""} placeholder="No sertifikat"/><input name="certificateUrl" type="url" defaultValue={item.certificateUrl ?? ""} placeholder="Link sertifikat"/><button>Simpan</button></form> : <span>{item.attendanceStatus} · {item.completionStatus}</span>}{canDelete && <ConfirmTrainingForm action="/api/training" method="post" message={`Keluarkan ${item.employee.fullName} dari pelatihan?`}><input type="hidden" name="action" value="DELETE_PARTICIPANT"/><input type="hidden" name="id" value={item.id}/><button className="danger-button">Keluarkan</button></ConfirmTrainingForm>}</article>)}{!program.participants.length && <div className="empty-state">Belum ada peserta.</div>}</div>
    </div></details>)}{!programs.length && <div className="empty-state">Belum ada program pelatihan.</div>}</div>
  </section></main>;
}
