import { appUrl } from "@/lib/app-url";
import { requirePermission } from "@/lib/authorization";
import { db } from "@/lib/db";
import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";

const schema=z.object({action:z.enum(["CREATE","APPROVE","REJECT","CANCEL","DELETE"]),id:z.string().optional(),employeeId:z.string().optional(),typeName:z.string().trim().max(100).optional(),workDate:z.string().optional(),startTime:z.string().regex(/^\d{2}:\d{2}$/).optional(),endTime:z.string().regex(/^\d{2}:\d{2}$/).optional(),reason:z.string().trim().max(500).optional(),reviewNotes:z.string().trim().max(500).optional()});
function minutes(value:string){const [h,m]=value.split(":").map(Number);return h*60+m;}
export async function POST(request:NextRequest){try{const p=schema.parse(Object.fromEntries(await request.formData())),permission=p.action==="CREATE"?"create":p.action==="DELETE"?"delete":p.action==="CANCEL"?"edit":"approve",tenant=await requirePermission("attendance",permission);
if(p.action==="CREATE"){if(!p.employeeId||!p.typeName||!p.workDate||!p.startTime||!p.endTime)throw new Error();const workDate=new Date(`${p.workDate}T00:00:00.000Z`),[employee,type]=await Promise.all([db.employee.findFirst({where:{id:p.employeeId,companyId:tenant.companyId,deletedAt:null}}),db.masterData.findFirst({where:{companyId:tenant.companyId,category:"OVERTIME_TYPE",name:{equals:p.typeName,mode:"insensitive"},isActive:true,deletedAt:null}})]);if(!employee||!type||!Number.isFinite(workDate.getTime()))throw new Error();let totalMinutes=minutes(p.endTime)-minutes(p.startTime);if(totalMinutes<=0)totalMinutes+=1440;if(totalMinutes>960)throw new Error();const duplicate=await db.overtimeRequest.count({where:{companyId:tenant.companyId,employeeId:employee.id,workDate,status:{in:["PENDING","APPROVED"]}}});if(duplicate)return NextResponse.redirect(new URL("/overtime?error=duplicate",appUrl(request)),303);const data={companyId:tenant.companyId,employeeId:employee.id,typeName:type.name,workDate,startTime:p.startTime,endTime:p.endTime,totalMinutes,reason:p.reason||null},item=await db.overtimeRequest.create({data});await db.auditLog.create({data:{companyId:tenant.companyId,actorUserId:tenant.session.userId,action:"CREATE",module:"overtime",entityType:"OvertimeRequest",entityId:item.id,newValue:{...data,workDate:p.workDate}}});}
else{const item=await db.overtimeRequest.findFirstOrThrow({where:{id:p.id,companyId:tenant.companyId}});if(["APPROVE","REJECT"].includes(p.action)&&item.status!=="PENDING")throw new Error();const next=p.action==="APPROVE"?"APPROVED":p.action==="REJECT"?"REJECTED":p.action==="CANCEL"?"CANCELLED":null;if(p.action==="DELETE")await db.overtimeRequest.delete({where:{id:item.id}});else await db.overtimeRequest.update({where:{id:item.id},data:{status:next!,reviewedById:tenant.session.userId,reviewNotes:p.reviewNotes||null,reviewedAt:new Date()}});await db.auditLog.create({data:{companyId:tenant.companyId,actorUserId:tenant.session.userId,action:p.action,module:"overtime",entityType:"OvertimeRequest",entityId:item.id,previousValue:{status:item.status},newValue:{status:next,reviewNotes:p.reviewNotes||null}}});}return NextResponse.redirect(new URL("/overtime?saved=1",appUrl(request)),303);}catch{return NextResponse.redirect(new URL("/overtime?error=1",appUrl(request)),303);}}
