import { requirePermission } from "@/lib/authorization";
import { db } from "@/lib/db";
import { hasPermission } from "@/lib/permissions";
import { redirect } from "next/navigation";
import { ConfirmShiftAction } from "./ConfirmShiftAction";

export default async function ShiftsPage({searchParams}:{searchParams:Promise<{saved?:string;error?:string}>}){
  let tenant;try{tenant=await requirePermission("shifts","view");}catch{redirect("/dashboard");}const query=await searchParams,permissions=tenant.membership.role.permissions,shifts=await db.shift.findMany({where:{companyId:tenant.companyId},orderBy:[{deletedAt:"asc"},{startTime:"asc"},{name:"asc"}]});
  return <main className="settings-page"><section className="settings-card"><header><div><span className="eyebrow">MASTER DATA</span><h1>Shift</h1><p>Atur jam kerja dan kapasitas shift khusus {tenant.membership.company.name}.</p></div><div className="header-actions"><a href="/schedules">Jadwal</a><a href="/master-data">Kembali</a></div></header>{query.saved&&<div className="form-success">Perubahan shift berhasil disimpan.</div>}{query.error&&<div className="form-error">{query.error==="used"?"Shift masih digunakan pada jadwal dan tidak dapat dihapus. Gunakan Nonaktifkan agar riwayat tetap aman.":query.error==="duplicate"?"Kode shift sudah digunakan.":"Perubahan shift gagal. Periksa seluruh isian."}</div>}<div className="department-rule-list">{shifts.map(shift=><article className="department-rule-card" key={shift.id}><div className="department-rule-title"><div><span style={{borderLeft:`5px solid ${shift.color}`,paddingLeft:8}}>{shift.code}</span><h2>{shift.name}</h2><small>{shift.deletedAt?"NONAKTIF":"AKTIF"}</small></div><b>{shift.startTime}–{shift.endTime}</b></div>{hasPermission(permissions,"shifts","edit")&&<details><summary>Edit shift</summary><form action="/api/shifts/manage" method="post" className="settings-form"><input type="hidden" name="id" value={shift.id}/><input type="hidden" name="action" value="UPDATE"/><label>Kode<input name="code" defaultValue={shift.code} required/></label><label>Nama<input name="name" defaultValue={shift.name} required/></label><label>Jam masuk<input type="time" name="startTime" defaultValue={shift.startTime} required/></label><label>Jam pulang<input type="time" name="endTime" defaultValue={shift.endTime} required/></label><label>Istirahat<input type="number" name="breakMinutes" defaultValue={shift.breakMinutes}/></label><label>Toleransi terlambat<input type="number" name="lateToleranceMin" defaultValue={shift.lateToleranceMin}/></label><label>Minimum staf<input type="number" name="minStaff" defaultValue={shift.minStaff}/></label><label>Maksimum staf<input type="number" name="maxStaff" defaultValue={shift.maxStaff??""}/></label><label>Warna<input type="color" name="color" defaultValue={shift.color}/></label><button>Simpan Perubahan</button></form></details>}<div className="header-actions">{hasPermission(permissions,"shifts","edit")&&<><ConfirmShiftAction id={shift.id} action="DUPLICATE" label="Duplikat" name={shift.name}/><ConfirmShiftAction id={shift.id} action="TOGGLE" label={shift.deletedAt?"Aktifkan":"Nonaktifkan"} name={shift.name}/></>}{hasPermission(permissions,"shifts","delete")&&<ConfirmShiftAction id={shift.id} action="DELETE" label="Hapus Permanen" name={shift.name} danger/>}</div></article>)}</div></section></main>;
}
